### ISSUE TITLE
No strongname version available via NuGet

### ISSUE THREAD

**Issue by binarytox1n** [kevin-montrose/Jil#103]
I would like to use Jil, but need to use strongly named libraries. Is it possible to release a NuGet package with a signed assembly?

**Comment by hbulzy** [comment]
anyone know how can run on .net40

**Comment by kevin-montrose** [comment]
@hbulzy Jil requires .net 4.5 or higher, there is no way to get it to run on .net 4.0.

**Comment by kevin-montrose** [comment]
@binarytox1n @tcsaddul There is now a Jil.StrongName project that produces signed .dlls, strongly named nuget packages will be published starting with the next release.

**Comment by kevin-montrose** [comment]
@binarytox1n @tcsaddul 

First release post-Jil.StrongName (2.7.1) is out, available on nuget.org at: https://www.nuget.org/packages/Jil.StrongName/
