### ISSUE TITLE
Jil Serialization and Deserialization takes time in loop

### ISSUE THREAD

**Issue by ravi032** [kevin-montrose/Jil#118]
Hi Kevin,

I was checking performance of Jil Serialization with Service Stack & Newtonsoft.Json.

I created a loop(10 times) inside that I did serialization & deserialization.

Example:

(Loop - 10 times)
{
    string input = "some serialized data";
    stopwatch.start();
    var result = JSON.Deserialize<MyType>(input);
    stopwatch.stop();
    //register this time in file
}

(Loop - 10 times)
{
    myClass obj = object of my class;
    stopwatch.start();
    var result = JSON.Serialize(obj);
    stopwatch.stop();
    //register this time in file
}

In this looping, when I see the time taken in my file, I observed that for first time serialization and deserialization takes considerable time and after that from 2 time it takes very less time.

Serialization Time in Milliseconds
280.0
0.04
0.04
0.04
0.04
0.04
0.04
0.04
0.04
0.04

Deserialization Time in Milliseconds
250.0
0.04
0.04
0.04
0.04
0.04
0.04
0.04
0.04
0.04

Kindly explain this reason?

**Comment by kevin-montrose** [comment]
From the [README](https://github.com/kevin-montrose/Jil/blob/master/README.md)

>The first time Jil is used to serialize a given configuration and type pair, it will spend extra time building the serializer. Subsequent invocations will be much faster, so if a consistently fast runtime is necessary in your code you may want to "prime the pump" with an earlier "throw away" serialization.

and

> The first time Jil is used to deserialize a given configuration and type pair, it will spend extra time building the deserializer. Subsequent invocations will be much faster, so if a consistently fast runtime is necessary in your code you may want to "prime the pump" with an earlier "throw away" deserialization.

The first invocation of a given Type/Option pair does a lot more work than subsequent calls.

**Comment by ravi032** [comment]
Thank you Kevin.
