### ISSUE TITLE
Support JilDirective in Deserialization

### ISSUE THREAD

**Issue by dsoronda** [kevin-montrose/Jil#120]
Let's say i have json file with this element : "24hr": { ... }
I need to properly deserialize it without using attribute on my POCO (I need clean domain).

I can use this
[Jil.JilDirective(Name = "24")]
public Day_24hr Day { get; set; }

But I would preffer to have something like this :
var directives = new Jil.Directives() { new NameDirective ("24", "Day_24") };

and then do deserialization with :
 var myObject = Jil.JSON.Deserialize<MyObject>( json,directives: );

Is this possible ? If it is, I don't see it in documentation.
Thanks.

**Comment by darkl** [comment]
I have a similar issue - I have properties that already have the [JsonProperty] attribute of Newtonsoft.Json. It would be nice to be able to customize the serialization/deserialization names. (by making some of the extension methods (or at least GetSerializationName) more polymorphic)
