### ISSUE TITLE
Any chance of supporting the $type feature of Json.net?

### ISSUE THREAD

**Issue by SimonCropp** [kevin-montrose/Jil#123]
http://www.newtonsoft.com/json/help/html/SerializeTypeNameHandling.htm

Happy to try to submit a PR

**Comment by kevin-montrose** [comment]
No.  If you need this feature you should probably just use [Json.NET](http://www.newtonsoft.com/json), which is my standard advice for anyone who needs much flexibility in their JSON serializer.

As a rule, Jil doesn't support JSON extensions.  I don't think an exception is worth making in this case.

Matching Newtonsoft's behavior would be pretty involved [given all the options](http://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_TypeNameHandling.htm) supported.  It would also be a pretty far-reaching change in Jil.

**Comment by SimonCropp** [comment]
@kevin-montrose yep that is a fair stance to take. thanks for considering it.  keep up the good work
