### ISSUE TITLE
Support for double.NaN, double.NegativeInfinity, and double.PositiveInfinity

### ISSUE THREAD

**Issue by elutsky** [kevin-montrose/Jil#124]
Hi
Probably its me doing something wrong or missing something. 
But in my case double.NaN (and Positive/Negative infinitive) are serialized to string, and not to number.

So, for example, when I am serializing list of dobles, contains double.NaN values - such values are serialized to string "NaN".

And when I am trying to deserialize it - It's failed since cannot convert string "NaN" to double.

Is it issue, known issue or my mistake?

Thanks!

**Comment by manofstick** [comment]
RFC 7159  (The JavaScript Object Notation (JSON) Data Interchange Format) in [section 6](https://tools.ietf.org/html/rfc7159#section-6) says *"Numeric values ... (such as Infinity and NaN) are not permitted."*

So really the serializer should fail I think.

**Comment by elutsky** [comment]
@manofstick Thanks for pointing for RFC.
From the other hand, its important values in some industries, and I was able to handle it right with other serializer (I did check in Newton).

I understand, that Jil is not Newton and did not try to be one, and has its own goals. Actually, we choose it for performance reasons and resource utilizations.

So I am wondering - is it any way to handle double "special values (properties)"  as NaN in the right way?

**Comment by kevin-montrose** [comment]
Jil shouldn't produce or accept invalid JSON, so I'm considering any sort of NaN-ish reading or writing a bug.  I don't think optional standard breaking is a path I want to take Jil down.

I believe [this method](https://github.com/kevin-montrose/Jil/blob/fba0cd114c36367cca53784345b10c8c020f4577/Jil/Serialize/Methods.cs#L1651) of checking is pretty cheap, though I need to do more extensive testing before pushing a new Nuget release.
