### ISSUE TITLE
ReadNumbers giving `Index was outside the bounds of the array.` error

### ISSUE THREAD

**Issue by nicholashead** [kevin-montrose/Jil#126]
I'm using the strongly-typed deserialization method, and running into this error. If I check the "SnippetAfterError", the item it appears to be choking on is a negative decimal. I have no idea what could be causing this. I cannot post the source code here for the view model/JSON since it's private, but I could submit to you via e-mail or private gist. What's the next step? Thanks!

**Comment by nicholashead** [comment]
(Inner Exception)
Message:	Index was outside the bounds of the array.
Source:	Jil
Type:	System.IndexOutOfRangeException
Line:	c:\Users\kevin_000\Dropbox\jil\Jil\Deserialize\Methods.ReadNumbers.cs:line 1940
Target:	_ReadDecimalFast
Stack Trace:	at Jil.Deserialize.Methods._ReadDecimalFast(TextReader reader, Char[]& buffer) in c:\Users\kevin_000\Dropbox\jil\Jil\Deserialize\Methods.ReadNumbers.cs:line 1940
at _DynamicMethod58(TextReader , Int32 )
at Jil.JSON.Deserialize[T](TextReader reader, Options options) in c:\Users\kevin_000\Dropbox\jil\Jil\JSON.cs:line 2031

(Outer Exception)
Message:	Index was outside the bounds of the array.
Source:	Jil
Type:	Jil.DeserializationException
Line:	c:\Users\kevin_000\Dropbox\jil\Jil\JSON.cs:line 2042
Target:	Deserialize
(ext) Jil Deserialize Errors:	jilDeserializationException.SnippetAfterError: '"20.00","Notes":"Issues on 243147","Total":-20,"Li'
Stack Trace:	at Jil.JSON.Deserialize[T](TextReader reader, Options options) in c:\Users\kevin_000\Dropbox\jil\Jil\JSON.cs:line 2042
at Jil.JSON.Deserialize[T](String text, Options options) in c:\Users\kevin_000\Dropbox\jil\Jil\JSON.cs:line 2067

**Comment by kevin-montrose** [comment]
A minimal reproduction would be helpful (model, JSON string, and the call to Jil [including `Options`, if any]).  If you prefer email `kevin.montrose` at `stackoverflow.com` will get to me.

**Comment by nicholashead** [comment]
Big thanks to @kevin-montrose for helping out with this. It was pretty much my JSON's fault, but the error message being returned from Jil wasn't helping me diagnose it.
