### ISSUE TITLE
Deserialization failed

### ISSUE THREAD

**Issue by Yeska** [kevin-montrose/Jil#128]
Hi,

First, thank you for this awsome library.

I have some problems deserializing this string, you can reproduce it using this code, not all the properties are used but I preferred to keep them all to preserve the same context. I'm using the master branch, and the Json is tested and valid :

Thank you,

I created a testmethod to reproduce the problem : 

http://pastebin.com/yzPpwFtG

**Comment by Yeska** [comment]
the error is :

Sigil.SigilVerificationException: CallVirtual expects 3 values on the stack
    à Sigil.Emit`1.UpdateStackAndInstrStream(Nullable`1 instr, TransitionWrapper transitions, Boolean firstParamIsThis) dans c:\Users\kmontrose\Dropbox\Sigil\Sigil\Emit.cs: line 918
   à Sigil.Emit`1.UpdateState(OpCode instr, MethodInfo method, IEnumerable`1 parameterTypes, TransitionWrapper transitions, Boolean firstParamIsThis, Type[] arglist) dans c:\Users\kmontrose\Dropbox\Sigil\Sigil\Emit.cs: line 1018

**Comment by Yeska** [comment]
A simpler way to reproduce it :

http://pastebin.com/qBRu6m6s

**Comment by kevin-montrose** [comment]
Thanks for the report and reproduction, the fix will be in the next release.  Hopefully that release will be sometime this week, schedule permitting.

**Comment by kevin-montrose** [comment]
@Yeska [2.10.0 contains this fix, and was just released](https://www.nuget.org/packages/Jil/2.10.0)

**Comment by Yeska** [comment]
Thank you, it works great.
