### ISSUE TITLE
Mono InvalidCastException issue

### ISSUE THREAD

**Issue by Zagitta** [kevin-montrose/Jil#130]
Hey first of all thanks for the amazing library! 

I've been trying to use Jil on Mono (4.0.1) recently and have run into a rather strange problem, namely that deserializing to `Dictionary<string, object>` where the value of a JSON key is a string and casting the object to string results in an InvalidCastException "Cannot cast from source type to destination type".

Here's a small code example that demonstrates the issue:
```
var dic = new Dictionary<string, object> ();
dic.Add ("abc", "123");

string s = (string)dic ["abc"]; //fine

var dic1 = Jil.JSON.Deserialize<IDictionary<string, object>>("{\"abc\": \"123\"}");
string s1 = (string) dic1["abc"]; //InvalidCastException
```

Do you have any clue what's causing this? Thanks in advance!

**Comment by kevin-montrose** [comment]
Mono isn't really supported (it sort of works, but I haven't had the time to really exhaustively test it...), but I'll guess here.

```
var dic1 = Jil.JSON.Deserialize<IDictionary<string, object>>("{\"abc\": \"123\"}");
string s1 = (string) dic1["abc"]; //InvalidCastException
```

You probably want dynamic dispatch there, either using `DeserializeDynamic(...)` or switching the call to `Deserialize<IDictionary<string, dynamic>>(...)` may solve your issue.
