### ISSUE TITLE
Discriminant Unions

### ISSUE THREAD

**Issue by kevin-montrose** [kevin-montrose/Jil#131]
@m0sa's implementation hacking up `Tuple<>` is [demonstrated here](https://github.com/m0sa/Jil/commit/0a417b5cda53c44ddc66be1f392f5c4d7f3df795).

I don't like using `Tuple<>` there, maybe something with `[JilDirective]` aliasing to the same name?  Also, gotta make it faster than dynamic stuff.

**Comment by kevin-montrose** [comment]
@m0sa [work in progress](https://github.com/kevin-montrose/Jil/tree/discriminant-unions) for my attempt.

[Examples in the tests](https://github.com/kevin-montrose/Jil/blob/6e92967bf1f69550d55211e9822dd17162ba6955/JilTests/DeserializeTests.cs#L5851), looks like:

```
class Foo
{
    [JilDirective(Name = "Data", IsUnion = true)]
    public string AsStr { get; set; }
    [JilDirective(Name = "Data", IsUnion = true)]
    public int AsInt { get; set; }
}
```


Still lots of work to do.

**Comment by m0sa** [comment]
One thing that we should consider here is how to detect which type the `Data` property contained. Perhaps an additional property would be handy for parsing the data, so you don't have to check each `As{Type}` against it's `default(Type)`:

    class Foo
    {
        [JilDirective(Name = "Data", IsUnion = true)]
        public string AsStr { get; set; }
        [JilDirective(Name = "Data", IsUnion = true)]
        public int AsInt { get; set; }
        [JilDirective(Name = "Data", IsUnion = true, IsUnionType = true)]
        public Type DataType { get; set; }
    }

Also, I think we need to know if the `Data` property had a value at all (as in `Data == null` in the `Tuple` case, `DataType == null` in example above)..

Both questions need an answer when you're consuming the code.

**Comment by kevin-montrose** [comment]
@m0sa I can see that as an optional config thing sure.  Pretty easy to setup too I think.

Right now I'm mostly focused on getting perf decent (currently emitting one branch per acceptable character... which is really bad).

My current implementation restricts unions to containing types that can be discriminated based on the first non-whitespace character read off the stream while parsing the member.  This matches my experiences with JSON (ie. a value will either be a string _or_ an array, or a number _or_ an object; rarely a string _or_ a date).  This is much more performant since I don't have to bail out of parsing (and thus don't need to buffer the stream), but naturally forbids some unions.  Thoughts?

**Comment by m0sa** [comment]
woohoo
