### ISSUE TITLE
object deserialization

### ISSUE THREAD

**Issue by yon86** [kevin-montrose/Jil#149]
I have an object that has an object inside like this

**public class customer**
**{**
**public string name {get;set;}**
**public object someProperty {get;set;}**

**}**

when I serialize and deseralize the object

**var obj = JSON.Deserialize<customer>(serializedString)**

I don;t get back the object somproperty I only get the json string...how can I get this to work

thanks

**Comment by Wazner** [comment]
This is because the default `Deserialize` method is highly optimized, it needs to know all possible types of a field before hand. To get the functionality you need, you should use the `DeserializeDynamic` method. 

Example:
```C#
var obj = JSON.DeserializeDynamic(jsonString);

Console.WriteLine(obj);
Console.WriteLine(obj.name);
Console.WriteLine(obj.someProperty);
```

**Comment by yon86** [comment]
I tried that before but it gives me the same result...if I change the object type to type of T it works during serialization and deserialization although I have to instantiate the class using that type T which I didn't want

here is what I am trying to do

I have 2 sample classes here the embedded one can handle that class or any other class depending on whats passed to it

public class embeddedCust
    {
        public string Name { get; set; }
        public int Age { get; set; }
        public string MyProperty { get; set; }
        public object Customer { get; set; }

    }
    public class Customer
    {
        public string name { get; set; }
        public int age { get; set; }

    }

then I have this

var data = new embeddedCust { Age = 11, Customer = new Customer { age = 12, name = "name" }, MyProperty = "myProperty", Name = "someName" };

 var serializedString = JSON.Serialize<embeddedCust>(data);

  var obj = JSON.Deserialize<embeddedCust>(serializedString);

I don't get the customer at all...

thanks for the help

**Comment by Wazner** [comment]
What you want to do is impossible. There is no way Jil knows what type of class will be used in `Customer` because it is of type `object`.

What you should use is `SerializeDynamic` and `DeserializeDynamic`.
Like so:
```C#
var data = new embeddedCust { 
    Age = 11, 
    Customer = new Customer { age = 12, name = "name" }
};
var serializedString = JSON.SerializeDynamic(data)
var dynObj = JSON.DeserializeDynamic(serializedString);

// dynObj won't be of type embeddedCust, but you can map it yourself
// if you know what kind of data it will be, for example:
var obj = new embeddedCust {
    Age = (int)dynObj.Age,
    Customer = new Customer {
        age = (int)dynObj.Customer.age,
        name = (string)dynObj.Customer.name
    }
}
```

*As a side note, I really recommend you use the [Microsoft Naming Conventions](https://msdn.microsoft.com/en-us/library/ms229045(v=vs.110).aspx), it makes your code a lot easier to read.*

**Comment by kevin-montrose** [comment]
Wazner is correct.
