### ISSUE TITLE
(De)Serialize DynamicObject

### ISSUE THREAD

**Issue by RefactorMan** [kevin-montrose/Jil#160]
Hi, I have a problem to (de)serialize DynamicObject with Jil.

This is my expandable object class:

	public class ExpandableObject : DynamicObject
	{
		private readonly Dictionary<string, object> _fields = new Dictionary<string, object>(StringComparer.OrdinalIgnoreCase);
		[JsonIgnore]
		public Dictionary<string, object> Extra { get { return _fields; } }

		public override IEnumerable<string> GetDynamicMemberNames()
		{
			var membersNames = GetType().GetProperties().Where(propInfo => propInfo.CustomAttributes
				.All(ca => ca.AttributeType != typeof (JsonIgnoreAttribute)))
				.Select(propInfo => propInfo.Name);
			return membersNames;
		}

		public override bool TryGetMember(GetMemberBinder binder, out object result)
		{
			return _fields.TryGetValue(binder.Name, out result);
		}

		public override bool TrySetMember(SetMemberBinder binder, object value)
		{
			_fields[binder.Name] = value;
			return true;
		}
	}

The problem is the overridden methods don't invoked.  With Newtonsoft.Json it works just great but the performance is bad...

For example - deserialize test of derived class:

	public class Person : ExpandableObject
	{
		public int Id { get; set; }
	}

	public class Program
	{
		public static void Main(string[] args)
		{
			var json = "{ \"Id\": 12 , \"SomeFiled\" : \"hello\" }";
			var person = Jil.JSON.Deserialize<Person>(json);            
		}
	}

There is any solution? or why this is happening?

**Comment by RefactorMan** [comment]
Hi, I tried to use "SerializeDynamic", and it has a similar problem -
no overrided method invoke but  "GetDynamicMemberNames".
Why is that?

    var json = JSON.SerializeDynamic(person, options);

In addition, the DeserializeDynamic method works but dont do what I need.
It returns 'dynamic'... any way to add an overrload that take <T> generic of IDynamicMetaObjectProvider ? many senarios need static type and not 'dynmic'.
Json.Net works like this in this case.

thanks.

**Comment by kevin-montrose** [comment]
At the moment this is by design.  `Deserialize<T>` is completely DLR unaware, Jil assumes `T` is statically defined in it's entirety.

Likewise, if an object is DLR aware `SerializeDynamic(object, Options)` will call into `GetDynamicMemberNames()` to enumerate what names are "meant" to be exposed, and then use the DLR to access them.

I could see adding support for calling `TrySetMember(...)` when deserializing as a new `Option`*, but it's not a very high priority.

`SerializeDynamic(...)` does work as you'd expect, your example doesn't expose the keys added dynamically.  Change your `GetDynamicMemberNames()` implementation to:

```csharp
public override IEnumerable<string> GetDynamicMemberNames()
{
    var membersNames =
        GetType()
            .GetProperties()
            .Where(propInfo =>
                propInfo.CustomAttributes.All(ca => ca.AttributeType != typeof(Newtonsoft.Json.JsonIgnoreAttribute))
            )
            .Select(propInfo => propInfo.Name).Concat(Extra.Keys).Distinct();
    return membersNames;
}
```

And you'll get any member added dynamically too.

<sub>*You'd want this behavior to be something opted into, not a default.</sub>

**Comment by Montrichard** [comment]
I've just tried this approach as I have a unknown type at runtime that I want to decorate when serialzing and I have the below:

```
public class Wrapper : DynamicObject
    {
        [DataMember(Name = "@id")]
        public string Id { get; set; }

        [DataMember(Name = "@context")]
        public string Context { get; set; }

        [DataMember(Name = "@type")]
        public string Type { get; set; }

        private readonly object _value;
        private readonly FastMember.TypeAccessor Accessor;
        private readonly string[] MemberNames;

        public Wrapper(object value)
        {
            _value = value;
            Accessor = TypeAccessor.Create(value.GetType());
            MemberNames = Accessor.GetMembers().Select(a => a.Name).Concat(GetType().GetProperties().Select(p=>p.Name)).ToArray();
        }

        public override IEnumerable<string> GetDynamicMemberNames()
        {
            return MemberNames;
            

        public override bool TryGetMember(GetMemberBinder binder, out object result)
        {
            if (MemberNames.Contains(binder.Name))
            {
                result = Accessor[_value, binder.Name];
                return true;
            }

            return base.TryGetMember(binder, out result);
        }
    }
```

I then call it like so:

````
var wrapper = new Wrapper(new Person() {Age = 1, Name = "poop"}) {Context = "mycontext"};

var output = JSON.SerializeDynamic(wrapper);
```

However the DataMember attributes are not used as it's using reflection to get the property names out.  Is there a way to get those attribute values? Thanks
