### ISSUE TITLE
Support for a Uri to be serialized as a string

### ISSUE THREAD

**Issue by rgmills** [kevin-montrose/Jil#163]
Trying to play around with converting our API to use Jil, however our existing contract expects a Uri to be serialized as a string.  Jil currently treats `System.Uri` as just another object and will serialize all of it's members.

Would you be open for PR to support this?  Or, is there an alternative way I can coerce Jil to serialize a `Uri` to a string?

Thanks!

**Comment by kevin-montrose** [comment]
I've resisted adding `Uri` to Jil as it's kind of... complicated.  Just making absolute vanilla http(s) work isn't too bad, but dealing with all the different states a Uri can be in gets hairy fast (relative vs absolute, preserving ports, [`OriginalString`](https://msdn.microsoft.com/en-us/library/system.uri.originalstring(v=vs.110).aspx) behavior, etc.).

I wouldn't reject a PR out of hand, but it'd get a pretty intense review and given how likely failure is I haven't really encouraged people to pursue it.  You're free to try though.

My suggestion for people in this bind is a string property that proxies for the Uri.

Example:
```csharp
public class HasUri
{
	[JilDirective(Ignore=true)]
	public Uri MyUri { get; set; }

	[JilDirective(Name="MyUri")]
	public string JustForSerializingMyUri
	{
		get
		{
			// Assuming that MyUri is always constructed via `new Uri(string)`
			return MyUri.OriginalString;
		}
		
		set
		{
			MyUri = new Uri(value);
		}
	}
}
```

**Comment by rgmills** [comment]
I started down that path of adding it, then ended up with what you suggested.  I honestly didn't even consider cases outside of HTTP(s) which seem to be interesting to say the least.
