### ISSUE TITLE
Deserialisation w/ CamelCase exception

### ISSUE THREAD

**Issue by scheepersw** [kevin-montrose/Jil#167]
Hi
I'm trying to deserialize using the new CamelCase options (Jil 2.11 thanks for the new release btw).  It works well except for this scenario.

my json string;
{"fromCache":false,"page":1,"pageSize":50,"sortField":"description","sortDirection":0,"filters":[]}

Jil.DeserializationException occurred
  EndedUnexpectedly=false
  HResult=-2146233088
  Message=Expected character: '"'
  SnippetAfterError=,"filters":[]}
  Source=Sigil.Emit.DynamicAssembly
  StackTrace:
       at _DynamicMethod70(ThunkReader& , Int32 )
       at Jil.JSON.Deserialize[T](String text, Options options) in c:\Users\kevin_000\Dropbox\jil\Jil\JSON.cs:line 4819
       at DynaMiX.Core.Http.JilSerializer.DeserializeCamelCase[T](String json)
  InnerException: 

This json string deserializes fine with Newtonsoft.

Let me know if there is any other details I can provide.

**Comment by kevin-montrose** [comment]
The definition(s) for the class(es) being deserialized would be handy, looks like Jil's complaining about `sortDirection`.

Shooting from the hip (this may actually be a bug, but if it's not...) `SortDirection` is an enum which Jil is expecting to have been serialized as a string.  Applying `[JilDirective(TreatEnumAs=<byte|int|short|etc.>)]` to `SortDirection`, or changing serialization to emit the string-equivalent would fix it.

**Comment by scheepersw** [comment]
Thanks for the reply. It is, as you suspected, the sortDirection enum is the problem. The [JilDirective(TreatEnumAs=<byte|int|short|etc.>)] fixes this.
