### ISSUE TITLE
Dynamic Deserialization of complex type and casting it to concrete type

### ISSUE THREAD

**Issue by Tornhoof** [kevin-montrose/Jil#171]
Hi,
I have a json where I do not know the (complex) type during compile time, but only during runtime, so I'm trying to use the DeserializeDynamic Feature, it deserializes fine to dynamic, but then I'm trying to cast to the concrete type (using the Typeconverter) and it fails in Jil.2.12.1

Example source:

            var testObject = new TestObject();
            testObject.Forms.Add(new AnotherTestObject {Key = "Hello", Value = "World"});
            string json = Jil.JSON.Serialize(testObject);

            var typed = Jil.JSON.Deserialize<TestObject>(json); // works

            var dynamic = Jil.JSON.DeserializeDynamic(json);
            var cast = (TestObject)dynamic; // Exception Unable to convert dynamic [Object] to [TestObject]

            var converter = TypeDescriptor.GetConverter(dynamic);
            bool can = converter.CanConvertTo(typeof (TestObject)); // false, should be true

The exception happens at: var cast = (TestObject)dynamic;

The supplied classes look like this:

    class TestObject
    {
        private List<AnotherTestObject> m_Objects;

        public List<AnotherTestObject> Forms
        {
            get { return m_Objects ?? (m_Objects = new List<AnotherTestObject>()); }
            set { m_Objects = value; }
        }
    }

    class AnotherTestObject
    {
        public string Key { get; set; }
        public string Value { get; set; }
    }

Am I wrong to assume that this should work?

**Comment by kevin-montrose** [comment]
At this time, Jil doesn't support casting it's `dynamic` returns to more complex types than those that make up JSON primitives (lists, dictionaries, strings, numbers, etc.).  TypeConverters are supported so that trial casts aren't necessary (as throwing exceptions on failed casts is very slow).

This isn't supported, but you can hack around it with some reflection.

```csharp
void Main()
{
	var typeKnownAtRuntime = typeof(TestObject);
	var proxyThunkMtd = ProxyClass.ThunkMtd.MakeGenericMethod(typeKnownAtRuntime);
	var thunk = (Func<string, object>)Delegate.CreateDelegate(typeof(Func<string, object>), proxyThunkMtd);
	
	var testObject = new TestObject();
    testObject.Forms.Add(new AnotherTestObject {Key = "Hello", Value = "World"});
    string json = Jil.JSON.Serialize(testObject);
		
	var dynamic = thunk(json);
    // dynamic is a TestObject
}

class TestObject
{
    private List<AnotherTestObject> m_Objects;

    public List<AnotherTestObject> Forms
    {
        get { return m_Objects ?? (m_Objects = new List<AnotherTestObject>()); }
        set { m_Objects = value; }
    }
}

class AnotherTestObject
{
    public string Key { get; set; }
    public string Value { get; set; }
}

static class ProxyClass
{
	public static readonly MethodInfo ThunkMtd = typeof(ProxyClass).GetMethod("Thunk", BindingFlags.NonPublic | BindingFlags.Static);
	static object Thunk<T>(string reader)
	{
		return Jil.JSON.Deserialize<T>(reader);
	}
}
```
