### ISSUE TITLE
Jil deserialized object as IValueProvider

### ISSUE THREAD

**Issue by jabolx** [kevin-montrose/Jil#172]
Hello,

For over two days I'm trying to figure out how to use Jil as a default deserializer for ModelBinding in MVC application. The best way to preserve all the validation capabilities of DefaultModelBinder seems to be the usage of IValueProvider class which would be filled by custom function in ValueProviderFactory. The problem is that I can't find a way to use a standarized way to generate IValueProvider implementation from Jil deserialized object.

As in ValueFactoryProvider the type is not yet known (and shouldn't be) common sense tells me I should use dynamic deserialization. Problem is I have a hard time to convert such an object into let's say DictionaryValueProvider<object>. I tried looping over all the elements of dynamic object recursively, but as nearly all useful fields/properties of Jil JsonObject are private I would have to use some really ugly reflection to check if it's an Array or Dictionary etc.

So my question is - is there some nice and clean way to do this with Jil and I'm missing something completely obvious?

Best Regards.

**Comment by kevin-montrose** [comment]
TypeConverters can be used to test dynamic object types, _however_ `dynamic` support in Jil only allows casts to simple types (typically those that correspond to JSON primitives).

You can see examples of how to interrogate Jil's dynamic returns for what they can be cast to [in this test](https://github.com/kevin-montrose/Jil/blob/39734fb29bb2602e1d2576454aeaaaf73391caab/JilTests/DeserializeDynamicTests.cs#L2548).
