### ISSUE TITLE
Strongly typed wrappers around primitives

### ISSUE THREAD

**Issue by Scooletz** [kevin-montrose/Jil#173]
Hi,
Have you considered creating a functionality similar to JsonConverter from JSON.NET which would enable to read/write primitives like string to a strongly-typed wrap? This could be useful for instance, to get strongly typed identifiers on the server side in the request, without additional mappings between the request and the message concumed by the service itself.
I was looking through the Jil code, and considered following scenario: 
- add either new fields to JilDirectiveAttribute or create a PrimitiveConvertableAttribute that could be added on the wrap type pointing to methods to ConvertFromPrimitive and ConvertToPrimitive
- change the InlineSerializer.Build to check for the PrimitiveConvertableAttribute and properly dispatch the build according to the type returned/accepted by the two convert methods.

This would result in passing the parsed primitive value to the method and using the result for the assignment. On the other hand, when serializing, the primitive value extraction, then writing the primitive would work.

What do you think about it? Is it worth a pull request? :-)

**Comment by kevin-montrose** [comment]
I would review a pull request that added this functionality to `[JilDirective]`.

**Comment by Scooletz** [comment]
Great, will do.

**Comment by Scooletz** [comment]
As you can see, I've sketched the serializer/writer part for this classes. The aim is simple: let's not blow Jil out of proportion with converters, but still, enable strong typing serialized objects with classes wrapping for instance identifiers.
Looking forward to hearing from you. If you like the design, I'd finish the deserializer part.
Any thoughts more than welcome!

**Comment by Wazner** [comment]
A suggestion is to support structure primitive wrappers aswell as classes. Structure wrappers prevent allocations.

**Comment by Scooletz** [comment]
Ok. Will do :-)
Beside that, do you see this approach valid and will it get merged when
done?
Any comments about style of introducing this?

Looking forward to hearing from you
12 paź 2015 00:11 "Jan" <notifications@github.com> napisał(a):
