### ISSUE TITLE
Exception when defining a property with `new`

### ISSUE THREAD

**Issue by kevin-montrose** [kevin-montrose/Jil#176]
[For example](http://i.imgur.com/4IGfDtP.png)

Proper behavior is _probably_ that this should work, _unless_ IncludeInherited is set in which case it's a conflict.  Hiding one or the other should property should also work.

**Comment by rossipedia** [comment]
Also, when serializing that kind of type (a derived `new` property with a different type), both properties are included in the output:

``` c#
void Main()
{
	JSON.Serialize<Derived>(new Derived(), Options.IncludeInherited).Dump();
}

class Base
{
	public int Foo { get; set; }
}

class Derived : Base
{
	public new string Foo { get; set; }
}
```

gives you:

``` json
{"Foo":0,"Foo":null}
```
