### ISSUE TITLE
right pattern for partial deserialization

### ISSUE THREAD

**Issue by BrannonKing** [kevin-montrose/Jil#177]
I have a scenario where I need to deserialize a method name out of an object before deserializing the parameters for that method because I need to look up the method to get the parameter types. What is the right pattern for this?

Using Json.NET I can do it like this: 
```csharp 
class MyMethod { 
  public string Method {get;set;} 
  public JArray Parameters {get;set;}
}
```
That allows me to serialize the parameters and then serialize the entire class with the parameters being a simple embedded object. I would like some way to do that with Jil. I need some data type that the serializer treats as "embedded JSON object". I can use a string, but then you will encode it. That seems expensive to me.

**Comment by Wazner** [comment]
Jil does not support partial deserialization like you're describing here. Instead Jil supports dynamic serialization using the DLR. It works as follows:
```C#
dynamic obj = JSON.DeserializeDynamic("{Method:\"Func2\",Parameters:[55, 99]}");

// Without knowing specifics, you can cast arguments
switch ((string)obj.Method) {
  case "Func1":
    Console.WriteLine("Date: {0}", (DateTime)obj.Arguments[0]);
    break;
  case "Func2":
    Console.WriteLine("Integers: {0}, {1}", (int)obj.Arguments[0], (int)obj.Arguments[1]);
    break;
}
```

Hope this helps

**Comment by BrannonKing** [comment]
Unfortunately, the DeserializeDynamic is insufficient for me. You cannot cast its result to arbitrary types. What we need are real hooks: 

1. a hook to handle the creation of a concrete type for an interface (rather than always using the proxy).
2. a hook to generate the exact JSON that is output for a certain type and the opposite: interpret the JSON by hand for a given object (and construct the right type if we don't have #1).

I can do what I need with #1 alone but it would still use JSON embedded in a JSON string, which is weird.
