### ISSUE TITLE
How Deserialize this with Jil

### ISSUE THREAD

**Issue by Gavrlex** [kevin-montrose/Jil#180]
Hello.
Please, help me deserialize this GeoJSON with Jil. Or give any example how deserialize GeoJSON format.

{ "type": "FeatureCollection",
    "features": [
      { "type": "Feature",
        "geometry": {"type": "Point", "coordinates": [102.0, 0.5]},
        "properties": {"prop0": "value0"}
        },
      { "type": "Feature",
        "geometry": {
          "type": "LineString",
          "coordinates": [
            [102.0, 0.0], [103.0, 1.0], [104.0, 0.0], [105.0, 1.0]
            ]
          },
        "properties": {
          "prop0": "value0",
          "prop1": 0.0
          }
        },
      { "type": "Feature",
         "geometry": {
           "type": "Polygon",
           "coordinates": [
             [ [100.0, 0.0], [101.0, 0.0], [101.0, 1.0],
               [100.0, 1.0], [100.0, 0.0] ]
             ]
         },
         "properties": {
           "prop0": "value0",
           "prop1": {"this": "that"}
           }
         }
       ]
     }

thanks in advance!

**Comment by Wazner** [comment]
Well, I don't know much about GeoJSON. You could either create a class hierarchy that represents the JSON format or you can use dynamic deserialization.

Dynamic deserialization is the easiest for dynamic data structures:
```C#
var myData = JSON.DeserializeDynamic(str);

// Now you can access myData.features, etc..
```
