### ISSUE TITLE
Jil doesn't serialize multidimensional arrays

### ISSUE THREAD

**Issue by caioproiete** [kevin-montrose/Jil#181]
Example:

```
var myArray = new decimal[2][,];
myArray[0] = new decimal[,] { { 10, 20 }, { 40, 50 } };
myArray[1] = new decimal[,] { { 15, 25 }, { 45, 55 } };

var serializedWithJil = JSON.Serialize(myArray);
// Result: [{},{}]

var serializedWithJss = new JavaScriptSerializer().Serialize(myArray);
// Result: [[10,20,40,50],[15,25,45,55]]
```

![image](https://cloud.githubusercontent.com/assets/177608/10838701/c784adde-7ea8-11e5-938d-b1b4c484d596.png)

**Comment by oliverjanik** [comment]
So `new decimal[,] { { 10, 20 }, { 40, 50 } }` produces `[10,20,40,50]`? How would that round-trip?

**Comment by kevin-montrose** [comment]
This is by design, JSON has no notion of a multidimensional (rather than a jagged) array.
