### ISSUE TITLE
GSON-compatible (de)serialization for float/double

### ISSUE THREAD

**Issue by jack-pappas** [kevin-montrose/Jil#182]
Although ``NaN`` and ``Infinity`` values aren't included in the [JSON spec](http://www.ecma-international.org/publications/standards/Ecma-404.htm), the widely-used [google/gson](https://github.com/google/gson) library supports serialization/deserialization of these values. Perhaps Jil could be modified to support them too? (I'm willing to contribute this if approved.)

Not only would this allow for compatibility with google/gson, but it'd also simplify writing the code that takes objects to be serialized and pushes them into Jil (or the reverse, for deserialization). Jil throws an exception now if you try to (de)serialize an object with a ``double`` or ``float`` field containing a ``NaN`` or ``Infinity`` value, so any glue code needs to either be very strict about validating objects before calling ``Serialize<T>(...)`` or make sure to call ``Serialize<T>(...)`` / ``Deserialize<T>(...)`` within a try/catch to handle the exceptions.

Reference (with comments about validity of (de)serializing ``NaN``, ``Infinity`` and ``-Infinity``):
https://github.com/google/gson/blob/2b15334a4981d4e0bd4f2c2d34b8978a4167f36a/gson/src/main/java/com/google/gson/GsonBuilder.java#L507-L530

**Comment by Wazner** [comment]
Jil is made for performance and does this by being strict about what it accepts.
Jil is a JSON serializer/deserializer and not a GSON serializer/deserializer.

Personally, I don't think Jil should go off the JSON standard.
But feel free to create a fork and add these options, maybe there are other people that require GSON serialization/deserializtion compatibility too.
