### ISSUE TITLE
CoreCLR  support

### ISSUE THREAD

**Issue by mgravell** [kevin-montrose/Jil#183]
This is mostly complete, but I'm adding this as a place-holder to track status.

A fully working branch is [available here](https://github.com/mgravell/Jil/tree/CoreCLR)

Items:
- [x] Create build structure (`project.json` etc)
- [x] Implement  code changes required to compile and run on CoreCLR
- [x] Get all tests passing
  - [ ] Except one test that I added as it was (and still is) giving a false positive - may warrant some thought on whether it is the test or the code that  is wrong - see [`ISO8601TimeSpansWithForcedZeroSeconds()`](https://github.com/mgravell/Jil/commit/f1093610c549d503e07fae635e2fb895cc4a8b9a)
- [x] Fix tooling to allow side-by-side builds (vs csproj) during transition - [am seeking input from dotnet/corefx](https://github.com/dotnet/corefx/issues/4544)
- [ ] Reinstate the decompiler
- [x] Reinstate some other bits I had to change (disassembly etc) due to platform restrictions - [am seeking input from dotnet/corefx](https://github.com/dotnet/corefx/issues/4543)
- [x] Update to rc1
  - [ ] future item: update to RTM bits
- [ ] Versioning / deployment
  - [x] Note that nupkg packaging comes for free - see `artifacts` after build

**Comment by CoreyKaylor** [comment]
Wondering if this was going to get anymore love now that coreclr RTM is out?

**Comment by aloisdg** [comment]
Any update?

**Comment by kevin-montrose** [comment]
[Jil 2.15.0](https://www.nuget.org/packages/Jil/2.15.0) supports .NET Core (netstandard 1.6).
