### ISSUE TITLE
Jil doesn't deserialize classes with C# 6.0's get-only Auto-Properties

### ISSUE THREAD

**Issue by jbattermann** [kevin-montrose/Jil#187]
I just noticed in a .net 4.6 / C#6 project that Jil appears to currently (2.12.1.0 / Sigil 4.5.0.0) not support C# 6's new autoproperty / { get; } - only properties, i.e.:

Instances of this class CAN be serialized (that do contain data in that byte array) but not correctly back - that .Data property is null after deserialization:
```
    public class CannotBeDeserialized
    {
        public byte[] Data { get; } // Jil serializes this properly, but deserializes it back / leaves it at 'null'

        // ..
    }
```

However, when specifying a (private) setter explicitely, deserialization DOES work as expected.
```
    public class CanBeDeserialized
    {
        public byte[] Data { get; private set; } // Jil serializes and deserializes the data as expected

        // ..
    }
```

**Comment by Wazner** [comment]
The reason is quite simple. 
If a property doesn't implement a setter, it can't be set.

When Jil deserializes an object it needs a way to store the deserialized values. When a property doesn't have a setter, it can't set the value of the property.
