### ISSUE TITLE
Add support for proper (de)serialization of Uri

### ISSUE THREAD

**Issue by HellBrick** [kevin-montrose/Jil#188]
At the moment Jil doesn't have any special knowledge about the `Uri` class, so it tries to (de)serialize it as a typical class, which leads to all its properties being serialized separately and to deserialization failing due to the lack of public parameterless constructor.

It would be incredibly useful to just serialize `Uri` instance as `Uri.AbsoluteUri` string and to be able to deserialize it back.

**Comment by kevin-montrose** [comment]
[Duplicate request](https://github.com/kevin-montrose/Jil/issues/163)

I'm remain disinclined to add Uri support, it's more complicated than it seems.
