### ISSUE TITLE
Enum problem

### ISSUE THREAD

**Issue by xxnihao323** [kevin-montrose/Jil#190]
public class OtherTest
    {
        [Xunit.Fact]
        public void TestEnum()
        {
            var t = new Temp() { A = A.Id | A.Name };
            /*error*/
            JSON.Serialize(t);
        }
    }

    public class Temp
    {
        public A A { get; set; }
    }
    public enum A
    {
        Id = 1,
        Name = 2,
    }

ok，it run error. thanks!

**Comment by kevin-montrose** [comment]
This is expected behavior, Jil treats enums as convenient ways to express strings (that is, the _JSON_ type is a string).  Because of that, any value not explicitly in the enum can't be converted to a string and thus cannot be serialized.
