### ISSUE TITLE
.NET 4.0

### ISSUE THREAD

**Issue by tshcherban** [kevin-montrose/Jil#192]
Can Jil target .NET 4.0?

**Comment by urielha** [comment]
+1 and .NET 3.5?

**Comment by force-net** [comment]
+1
I looked for code and found, that main issues only with reflection methods (can be rewrited) and AggressiveInlining attribute.

**Comment by tshcherban** [comment]
Yep, that's why I'm asking
I'll try measure performance impact of these changes and will inform about results asap

**Comment by tshcherban** [comment]
I've done some minimal benchmarking. Seems performance was not seriously affecter by removing 'AggressiveInlining' MethodImpl options. However, it should be retested more carefully (if author will approve migration/fork to .NET4).

**Comment by kevin-montrose** [comment]
Per https://github.com/kevin-montrose/Jil/pull/198 ; not at this time, but will revisit once core-clr settles down.
