### ISSUE TITLE
Escaping?

### ISSUE THREAD

**Issue by ProVega** [kevin-montrose/Jil#194]
I have an object (MyObject) with a MyJson property that is a string of unescaped JSON.  When I serialize my object, the MyJson value is properly escaped (\").  However when I later call deserialize on the MyObject, the MyJson string is returned escaped.  It would seem to me that this is a bug and if the serializes applies an escape, the deserializer should un-apply it.

Thoughts?

**Comment by kevin-montrose** [comment]
I'll need an example of this to comment.

**Comment by muhamadahsan** [comment]
@kevin-montrose : I just got the same issue today as well.... If you want to give it a try, use the following code:
`var data = new Dictionary<string, object>();
data["key1"] = new List<string> {"item1", "item2"};`

when you do the deserialization, you will find the escaped characters not removed.
