### ISSUE TITLE
Very slow startup time

### ISSUE THREAD

**Issue by markvincze** [kevin-montrose/Jil#196]
I'm trying to use the Jil serializer to improve performance compared to Json.NET, but I'm facing a weird issue. When I'm deserializing, the first deserialization is extremely slow, it takes 28-30 seconds.
The class I'm serializing is a simple POCO with strings, numbers, and lists, however, the object is pretty large, serialized to Json it's ~200 KBytes. All the subsequent serializations are fast, only the first one is slow.

I'm testing the timings with the following code:

    JsonTestJil(testObj);
    JsonTestJil(testObj);

    JsonTestJsonNet(testObj);
    JsonTestJsonNet(testObj);

    ...

    private static void JsonTestJil(MyPoco obj)
    {
        byte[] jsonBytes;

        using (var ms = new MemoryStream())
        {
            using (var sw = new StreamWriter(ms))
            {
                Stopwatch stop = Stopwatch.StartNew();

                JSON.Serialize(obj, sw, new Options());
                sw.Flush();

                stop.Stop();

                Console.WriteLine("JIL Serialize elapsed: {0}", stop.Elapsed);

                jsonBytes = ms.ToArray();
            }
        }

        using (var ms = new MemoryStream(jsonBytes))
        {
            using (var reader = new StreamReader(ms))
            {
                Stopwatch stop = Stopwatch.StartNew();

                var fr = JSON.Deserialize<MyPoco>(reader, new Options());

                stop.Stop();

                Console.WriteLine("JIL Deserialize elapsed: {0}", stop.Elapsed);
            }
        }
    }

    private static void JsonTestJsonNet(MyPoco obj)
    {
        byte[] jsonBytes;

        JsonSerializer serializer = new JsonSerializer();

        using (var ms = new MemoryStream())
        {
            using (var sw = new StreamWriter(ms))
            {
                using (var jtw = new JsonTextWriter(sw))
                {
                    Stopwatch stop = Stopwatch.StartNew();

                    serializer.Serialize(jtw, obj);
                    sw.Flush();

                    jsonBytes = ms.ToArray();

                    stop.Stop();

                    Console.WriteLine("Json.NET Serialize elapsed: {0}", stop.Elapsed);
                }
            }
        }

        using (var ms = new MemoryStream(jsonBytes))
        {
            using (var reader = new StreamReader(ms))
            {
                using (var jtr = new JsonTextReader(reader))
                {
                    Stopwatch stop = Stopwatch.StartNew();

                    var fr = serializer.Deserialize<MyPoco>(jtr);

                    stop.Stop();

                    Console.WriteLine("Json.NET Deserialize elapsed: {0}", stop.Elapsed);
                }
            }
        }
    }

This is the result I get:

    JIL Serialize elapsed: 00:00:00.9086457
    JIL Deserialize elapsed: 00:00:28.2087760
    JIL Serialize elapsed: 00:00:00.0026372
    JIL Deserialize elapsed: 00:00:00.0058671
    Json.NET Serialize elapsed: 00:00:00.0238354
    Json.NET Deserialize elapsed: 00:00:00.0085990
    Json.NET Serialize elapsed: 00:00:00.0050889
    Json.NET Deserialize elapsed: 00:00:00.0077529

So after the first run, the subsequent operations are significantly faster than Json.NET, however, the first one is very slow.

Is this normal? Is there any way to avoid this? I guess I could do a warmup serialization at the startup of my application, but I don't want to increase the warmup time of my application with half a minute. Also, even if I do the warmup, am I guaranteed that I won't get any other hiccups during the lifetime of my application?

(28 seconds seemed like really extreme, that's why I posted this as an Issue, if this is completely normal behavior, then I can remove it from here and post it as a question on SO or something.)

Thanks for any suggestions!

**Comment by Wazner** [comment]
Jil compiles a DynamicMethod (using kevin-montrose/Sigil) when an object is serialized/deserialized for the first time. This could take a significant amount of time when your object graph is large. There have been people talking about compiling these DynamicMethods to an assembly, but no one really got it to work/had enough time.

We can't do much without knowing your object graph (the object you're deserializing). Knowing your object graph, we could profile for any possible performance issues.
