### ISSUE TITLE
Add option UnspecifiedDateTimeKindBehavior.IsUnspecified

### ISSUE THREAD

**Issue by AxelMarquez** [kevin-montrose/Jil#201]
Looking at issue #129. There are some cases where an unspecified datetime is really that, deliberately unspecified, and we expect it to be correctly serialized to Iso8601 without the zone specified.

Unfortunately this is not possible as ALL datetimes are converted to UTC and serialized as such.

Please consider adding UnspecifiedDateTimeKindBehavior.IsUnspecified.

**Comment by ronald7** [comment]
I agree with AxelMarquez, that would be very useful. Please consider adding this option.
