### ISSUE TITLE
Ignore properties with null value.

### ISSUE THREAD

**Issue by GuyAssaf** [kevin-montrose/Jil#202]
In many cases you would like not to send properties that have no value.
An attribute to ignore a property with null value would be great.
The general option for all properties may not suit in some cases.

**Comment by kevin-montrose** [comment]
Controlling per-member serialization in Jil is done [via conditional serialization](https://msdn.microsoft.com/en-us/library/53b8022e(v=vs.110).aspx).

For any given property named XXX, you can define a method `bool ShouldSerializeXXX() { return XXX != null; }` to suppress serialization in the null case.

[See for example, this test](https://github.com/kevin-montrose/Jil/blob/31e76dd331ee2ca5e7779e849b0ab05ba0d9f753/JilTests/SerializeTests.cs#L2588)
