### ISSUE TITLE
Deserializing an empty Flags enum fails

### ISSUE THREAD

**Issue by deevus** [kevin-montrose/Jil#203]
I have a Flags enum which is something like the following:

```
[Flags]
public enum SomeEnum
{
    Type1 = 1 << 0,
    Type2 = 1 << 1,
    Type3 = 1 << 2,
    Type4 = 1 << 3
}
```

As such there is no "empty" value. Jil does not handle this well when deserializing an empty string when no flags are set. It should happily return zero and not throw an exception.

**Comment by Wazner** [comment]
I don't know if it should happily throw an Exception. I think it was a mistake of the .NET team to allow for non-defined values, its a breach of contract.

How come you can't modify your enum, even though 0 is apparently a valid value?

**Comment by deevus** [comment]
I'm using Jil to serialise a data model from EntityFramework into Redis for caching purposes. 

It is my understanding that a 0 value would just mean "none". I haven't had to explicitly add an entry for it in any other case so far.

**Comment by deevus** [comment]
https://msdn.microsoft.com/en-us/library/ms182149.aspx

A `None` value is not required for enums with `FlagsAttribute`.

**Comment by Wazner** [comment]
You're right that the .NET framework doesn't require a None member in enums with the `FlagsAttribute` (but it is recommended).

In the end, its up to @kevin-montrose to decide, whether to implement this, but I personally see enumerations as a contract and any undefined values as a code smell.

**Comment by deevus** [comment]
Do you have a reference that states that the `None` member is recommended?

**Comment by mburbea** [comment]
Microsoft code analysis recommends it.
https://msdn.microsoft.com/en-us/library/ms182149.aspx

That said, I think it makes sense to support the empty string case.

**Comment by kevin-montrose** [comment]
Because Jil produces a `""` when serializing `(SomeEnum)0` this is a bug, even it makes my teeth itch a bit (I'd still define a `None` in my code).  Digging.
