### ISSUE TITLE
Support for deserializing via constructor

### ISSUE THREAD

**Issue by sds88** [kevin-montrose/Jil#204]
C#6 added support to easily create immutable objects via get-only auto properties.  It would be nice for Jil to be able to use a constructor when deserializing so we can take advantage of immutable types.

Example for how Json.Net handles this:
```
public class Foo 
{
  public int Bar { get; }

  [JsonConstructor]
  public Foo(int bar) 
  {
    Bar = bar;
  }
}
```

**Comment by NimaAra** [comment]
This will be a really good feature to have as I am now forced to specify 2 set of classes for each of my models, a DTO with public getter/setters and an immutable POCO built from the DTO so that I can have an immutable model which I can pass around.

**Comment by kevin-montrose** [comment]
You can do this for primitive types with [`[JilPrimitiveWrapper]`](https://github.com/kevin-montrose/Jil/blob/master/Jil/JilDirectiveAttribute.cs#L93).

[See this test for example](https://github.com/kevin-montrose/Jil/blob/31e76dd331ee2ca5e7779e849b0ab05ba0d9f753/JilTests/DeserializeTests.cs#L3287)

**Comment by NimaAra** [comment]
That's very useful and I will surely take a look but does it only support primitive types? how about immutable reference types?
