### ISSUE TITLE
Use FormatterServices.GetUnitializedObject instead of constructor with default values.

### ISSUE THREAD

**Issue by Wazner** [kevin-montrose/Jil#207]
Currently when Jil determines the field addresses for optimal order, it will try to create an instance of the type using the constructor with the least amount of arguments. (See: [Utils.cs line 467](https://github.com/kevin-montrose/Jil/blob/203d47c9f109401fa8045a1a3f079e63678b1f14/Jil/Common/Utils.cs#L467))

This will fail when the constructor does anything with the objects, for example:

``` C#
class Test {
    private readonly int _a;

    public Test(OtherType b) {
        _a = b.A;
    }

    public int A {
        get { return _a; }
    }
}
```

I suggest using [`FormatterServices.GetUninitializedObject`](https://msdn.microsoft.com/en-us/library/system.runtime.serialization.formatterservices.getuninitializedobject.aspx) instead, this will create an instance of the object without calling any constructor, all fields will be initialized with its default value. The only downside to this is that the call will take about 11% longer than just using `Activator.CreateInstance`. A possible hybrid is to use `Activator.CreateInstance` when there is a default constructor, otherwise use `FormatterServices.GetUninitializedObject`.

This change allows objects that will never be deserialized anyway, be serialized without adding an empty constructor just for serialization.

I'm posting this as an issue so there is a place for discussion, I'm happy to post a pull request when you think this is an useful change @kevin-montrose.

**Comment by kevin-montrose** [comment]
Sounds like a good idea to me, I'd consider a pull request.

**Comment by Timovzl** [comment]
I would definitely opt for always using `GetUninitializedObject`. I've had issues with the default constructor "doing things" and then being hit by deserialization (and, shockingly, even by _serialization_).
