### ISSUE TITLE
Create object via factory

### ISSUE THREAD

**Issue by DCollart** [kevin-montrose/Jil#208]
Hello,

I added Jil to my project and I have the classical error "Expected a parameterless constructor".

I use interfaces instead of concrete classes so this result is totally natural.

My question is : Is there a way to use a factory (or another way) to create object for a specific type ?

Thanks :-)

(Sorry for my bad english)

**Comment by kevin-montrose** [comment]
Jil should try and create default implementations of interfaces when needed, can you provide code to reproduce of this error?

**Comment by cubed-it** [comment]
I'm trying Jil as an alternative and have a similar problem. Why is it looking for a constructor for an interface? It is even null.

`void Main()
{
	var obj = new TestClass(){test1 = 10};

	var json = JSON.Serialize<TestClass>(obj);
	Console.WriteLine(json);
	var obj2 = JSON.Deserialize<TestClass>(json);	
}

public class TestClass
{
	public int test1 { get; set; }
	public Dummy test12 { get; set; }
	public IDummy test13 { get; set; }
}

public class Dummy : IDummy
{
	public Dummy()
	{		
	}
}

public interface IDummy
{
}`
