### ISSUE TITLE
 [Flags] enum : long does not deserialize

### ISSUE THREAD

**Issue by okinkela** [kevin-montrose/Jil#210]
class Program
    {
        [Flags]
        public enum Works
        {
            A = 1,
            B = 2
        }
        [Flags]
        public enum Broken : long
        {
            A = 1,
            B = 2
        }

        static void Main(string[] args)
        {
            Works works = Jil.JSON.Deserialize<Works>(Jil.JSON.Serialize<Works>(Works.A));
            Broken broken = Jil.JSON.Deserialize<Broken>(Jil.JSON.Serialize<Broken>(Broken.A));
        }
    }

**Comment by Wazner** [comment]
Is this a duplicate of #206 ?

**Comment by Soenneker** [comment]
@Wazner Yes.

**Comment by kevin-montrose** [comment]
Was fixed by #206
