### ISSUE TITLE
Serializing dictionary with CamelCase option

### ISSUE THREAD

**Issue by sds88** [kevin-montrose/Jil#211]
When serializing a dictionary, It seems that the `SerializationNameFormat.CamelCase` option does not apply to the keys.  Would it be possible to either update this option to include dictionary keys, or to have a separate option specifically for the casing of dictionary keys?

For reference if I have this dictionary:

```
var dict = new Dictionary<string, string>();
dict["Foo"] = "Bar";
```

Jil currently will output the following with the `SerializationNameFormat.CamelCase` option selected:

```
{
  "Foo": "Bar"
}
```

What I would like is for this output:

```
{
  "foo": "Bar"
}
```

That is a very basic example, in our current situation that would like this we can't simply define the key in camel case.

**Comment by Wazner** [comment]
I think this should be a seperate option, if it will be implemented. I see dictionaries more like data instead of structure.

In some of my projects I rely on the fact that dictionaries are not camel cased.

**Comment by sds88** [comment]
For reference, the case we would like this option for is we have an Asp.Net Web Api where we replaced the default serializer with Jil.  

It currently works wonderfully with everything except when serializing exceptions.  To return an error response with a web api, you `throw new HttpResponseException(...)`, which gets converted into a `HttpError` by the runtime before serialization.  This `HttpError` internally is a dictionary that contains the key `Message` and value depending on what you put in the exception.  As a result, all of our api's responses are camel cased except errors, which show up as `{ "Message": "Error message"}`
