### ISSUE TITLE
Deserialize error

### ISSUE THREAD

**Issue by edobnet** [kevin-montrose/Jil#212]
error: Expected: ", null
json:
{
    "resultCode": 0,
    "resultInfo": {
        "holdTime": "2015-11-01 18:00:00",
        "idType": "11",
        "sex": "1",
        "paySta": "0",
        "deposit": 0.00,
        "remark": "【仅限会员卡本人入住】/来自去哪儿",
        "rmtype": "SCF",
        "hotelDescript": "成都玉林倪家桥地铁站店",
        "cityCode": "CDSC",
        "staDescript": "未到",
        "rsvMan": "侯海军",
        "sexDescript": "男",
        "rateCode": "MEMV1",
        "couponVaule": 0,
        "rate": 79.00,
        "cardrNo": "61397800",
        "rmNum": 1,
        "everyDayRate": "79.00",
        "createDatetime": "2015-11-01",
        "name": "侯海军",
        "rmtypeDescript": "双床房",
        "dep": "2015-11-02",
        "rsvType": "90",
        "idNo": "513701198306242939",
        "crsNo": "O15110101523814786S",
        "sta": "N",
        "hotelCode": "CNSCCDB381",
        "arr": "2015-11-01",
        "modifyDatetime": "2015-11-02",
        "couponCharge": 0,
        "hotelGroupCode": "ZHUYOUG",
        "charge": 0.00,
        "email": "",
        "cardrType": "",
        "cityDescript": "成都",
        "maxDep": "2015-11-02",
        "rateSum": 0.00,
        "night": 0,
        "companyId": 0,
        "minArr": "2015-11-01",
        "mobile": "18910545212"
    }
}
json.net Is OK ,I will use jil replace json.net  BUT IS error

**Comment by edobnet** [comment]
![qq 20160310162933](https://cloud.githubusercontent.com/assets/1813525/13663591/5ede3960-e6dd-11e5-8a93-df4369e0da4f.png)

**Comment by edobnet** [comment]
"companyId": 0
   public string companyId { get; set; }
can not transfer auto

**Comment by kevin-montrose** [comment]
Need the model type and callsite to debug.
