### ISSUE TITLE
Weird behaviour in Utils.cs method PropertyFieldUsage

### ISSUE THREAD

**Issue by Tornhoof** [kevin-montrose/Jil#213]
Hi,
I use Jil to serialize quite a few different models, including dynamically generated types.
After adding a completely unrelated model, I now receive several (hundreds) of ArgumentOutOfRangeException in method PropertyFieldUsage line 200 in Utils.cs:
System.ArgumentOutOfRangeException occurred
  HResult=-2146233086
  Message=Das Token 0x0400021c ist im Bereich von Modul My.Project.Dynamic.dll ungültig.
Parametername: metadataToken
  ParamName=metadataToken
  Source=mscorlib
  StackTrace:
       bei System.Reflection.RuntimeModule.ResolveField(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
  InnerException: 

(sorry that the error message is in german).

I saw the comment and apparently it has no further consequences, but I thought I report it anyway.

I can trigger that behaviour by commenting/uncommenting a completely unrelated property.
The type where it happens is a generic type, which is generated dynamically.
The properties in question are all defined in non-abstract base classes (not dynamic) and include different property types (e.g. nullable enum, List<string>, Guid, string, int?)

The Fieldhandles are all valid field handles if I look it up directly in the base class and point to automatic backing fields.

As previously said if I comment specific property in an unrelated class (they don't share the same base class, not even the name is the same, nor the type and the class is not in a dynamic module), the properties above do not throw these errors.

What I don't really understand is, that in the good case (without the error) the fieldhandle is resolved using your method, but the resolved fieldinfo has nothing to do with the property in question, unrelated class, unrelated field (e.g. property with the Error is called ErrorEnum, the field which is resolved is Country). Next funny thing is this Country property is actually of the same type of the one i need to comment out (but not the same declaring type).

I don't even assume for what you need that mapping, as far as I understand you use it for memory-optimized serialization layouts?

I tried to build a repro case, but failed miserably.

Best Regards,
torni

**Comment by mjashanks** [comment]
I am experiencing a very similar sounding issue... but also completely different!

I am using ZeroMQ (https://github.com/zeromq/libzmq) with F# bindings (https://github.com/zeromq/fszmq)

ZeroMQ is basically a wrapper library for sockets - written in C++

ZeroMQ works perfectly, until I introduce Jil. All I have to do is serialize an object before I send a message. Note - **I dont even have to send the object that I serialized** ... all i have to do is serialize a random object, and then send a message.

For some reason, this kills ZeroMQ about 1 in every 4 times. Interestingly, it happens about 9/10 times if i then add some add a line like `Encoding.UTF8.GetBytes( jilSerializedObject )`

When i comment the serialization line out, it all works 100%.

I will put some effort into building a solid repro.
