### ISSUE TITLE
JSON.Deserialize should return null if TextReader is empty.

### ISSUE THREAD

**Issue by oliverjanik** [kevin-montrose/Jil#217]
I'm doing this: 

``` csharp
JSON.Deserialize(new StreamReader(readStream), type, jilOptions)
```

and when readStream is empty i'm getting `Expected: {, null; but the reader ended` exception.

Is this the intended behaviour?

Do I need to try catch this to return null?

**Comment by kevin-montrose** [comment]
You should check if the stream is empty before attempting to deserialize from it.  Jil assumes its input is valid JSON, which an empty stream does not provide.

[`StreamReader.EndOfStream`](https://msdn.microsoft.com/en-us/library/system.io.streamreader.endofstream(v=vs.110).aspx) could be helpful.
