### ISSUE TITLE
Dynamic inquire about type or node type?

### ISSUE THREAD

**Issue by oliverjanik** [kevin-montrose/Jil#218]
Once I serialized into dynamic, internally this is a JsonObject instance. Is there a way inquire about node type or find out whether it's an array, object or primitive?

I know JsonObject supports casts I'd like to avoid exception catching if I need to test for several different possibilities.

**Comment by kevin-montrose** [comment]
Dynamic inspection is supported through [`TypeConverter`s](https://msdn.microsoft.com/en-us/library/system.componentmodel.typeconverter(v=vs.110).aspx).

You can find [examples in this test](https://github.com/kevin-montrose/Jil/blob/afc30d08130f6c154844d31e2433fd3052eca586/JilTests/DeserializeDynamicTests.cs#L2548).

**Comment by oliverjanik** [comment]
Thanks a bit clunky but works.

**Comment by kevin-montrose** [comment]
Yeah, I wish I could make the `is` and `as` keywords do that lifting - but there's no way to hook into them w.r.t. dynamic dispatch.  So since I'm stuck with clunky, I went with the clunk that's built in.

**Comment by oliverjanik** [comment]
Any chance you'd consider making JsonObject public instead of internal?

**Comment by kevin-montrose** [comment]
Nah, it's too unstable in practice.  Some funky reflection in there too, that I suspect is gonna get real fun with a core port in the future.

**Comment by oliverjanik** [comment]
Then maybe something like serialization into internal structure a la JToken from you know which library.
