### ISSUE TITLE
enum serialization

### ISSUE THREAD

**Issue by Nazgaul** [kevin-montrose/Jil#221]
Hi.
Im doing a pilot of converting my app from json.net to jil.
everything is works as expected but one thing is missing.
on json.net you can specify that upon serialize the enum string result will be camel case.
on jil i dont see this option. so if i have an enum with value Academic - on json.net the json is academic and on jil is Academic.
is there a way to work around it?

**Comment by lazytom** [comment]
There is a CamelCase option mentioned in the readme - is that what you are looking for?

> Jil's JSON.Serialize and JSON.Deserialize methods take an optional Options parameter which controls:
> [...]
> The way to format member names; one of
> Verbatim
> As it appears in source, unless modified by a [MemberName] or [JilDirective]
> CamelCase
> lowercasing the first letter of members, ie. "CamelCase" would become "camelCase"
