### ISSUE TITLE
Unable to serilize JObject type data

### ISSUE THREAD

**Issue by Amit1150** [kevin-montrose/Jil#224]
I'm returing [JObject ](http://www.newtonsoft.com/json/help/html/t_newtonsoft_json_linq_jobject.htm) type data from API. But when I see the `response`, It remove the Key from `response data`.  It only return values. 

Or there any alternate for JObject in `JIl`

This is what I have written in my action.

```
 public IHttpActionResult TestValid(Student stru)
        {
            JObject tokenResponse = new JObject(
                                new JProperty("userName", "test@123"),
                                new JProperty("access_token", "my access token"),
                                new JProperty("token_type", "bearer"));
            return Ok(tokenResponse);
        }



```

This is response output I'm getting

```
[
  "test@123",
  "my access token",
  "bearer"
]
```

Where this is expected output

```
{
  "userName": "test@123",
  "access_token": "my access token",
  "token_type": "bearer"
}
```

And I have followed this Tutorial , [**How to replace Json.Net with Jil**](http://blog.developers.ba/replace-json-net-jil-json-serializer-asp-net-web-api/)

**Comment by kevin-montrose** [comment]
You'll have to post reproducing code, I can't tell what your issue is from this description.

**Comment by Amit1150** [comment]
I have updated my question. Please see it.
