### ISSUE TITLE
Make it .NETCoreApp compatible?

### ISSUE THREAD

**Issue by hismichael** [kevin-montrose/Jil#232]
Can you make this great tool compatible with .netcoreapp1.0?

**Comment by agoretsky** [comment]
+1

**Comment by El-Wray** [comment]
+1

**Comment by dsoronda** [comment]
+1

**Comment by ersintarhan** [comment]
+1

**Comment by claycephas** [comment]
+1

**Comment by EugeneKrapivin** [comment]
+1

I'm porting a dependent library ([StackExchange.Redis.Extensions](https://github.com/imperugo/StackExchange.Redis.Extensions)) to .net core and the only serializer missing is `Jil`.

**Comment by david-montiel** [comment]
+1

**Comment by aloisdg** [comment]
@mgravell (protobuf-net dev) started a port at #183

**Comment by aloisdg** [comment]
[NetJSON](https://github.com/rpgmaker/NetJSON) support .Net Core. It could be an alternative.

**Comment by kevin-montrose** [comment]
[Jil 2.15.0](https://www.nuget.org/packages/Jil/2.15.0) has support for .NET Core (netstandard 1.6).
