### ISSUE TITLE
Deserialize with case ignored

### ISSUE THREAD

**Issue by renkun-ken** [kevin-montrose/Jil#237]
Newtonsoft.Json by default ignores the case of data members when deserializing a json text. When I switch to Jil, I notice that only default or camelCase options are available, which sometimes makes it harder to switch to Jil from Newtonsoft.Json if many json files have field names that are inconsistent in cases with class fields.

Is it possible to deserialize a json with case insensitive or ignored?

**Comment by brucejing** [comment]
+1, I just met such situation and looking for a solution.

**Comment by jmalStorm** [comment]
+1, Is it possible to ignore case when deserializing?
