### ISSUE TITLE
Jil formatter does not support Order and EmitDefaultValue properties of DataMember.

### ISSUE THREAD

**Issue by ajaychoudhary01** [kevin-montrose/Jil#242]
I am using Json.Net Formatter and i want to reduce my response size by omitting null  values from response. I also want to send response in an order. But when i moved to JIL formatter, it doesn't support Order and EmitDefaultValue property of DataMember. It is a breaking change in my application. Please add this support so that i can use it in my application for performance gain.

**Comment by Tornhoof** [comment]
The undefined order of properties is specifically declared on the usage help of jil on the main page.
JSON.net also supports null value handling, see: http://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_NullValueHandling.htm

**Comment by ajaychoudhary01** [comment]
What if I want to expose some null values in my response. I don't want to add extra code to explicitly ignore null value. This should be handled by DataMemeber attribute itself. In some scenarios, we have to expose null values and in other, we have to omit null values from the response.
There should be a generic solution.

**Comment by ajaychoudhary01** [comment]
Any Updates on this?

**Comment by ajaychoudhary01** [comment]
Any Updates on this @Tornhoof

**Comment by kevin-montrose** [comment]
Order is explicitly not suppored, as Tornhoof noted.

You can elide `null` values with various [`Options`](https://github.com/kevin-montrose/Jil/blob/master/Jil/Options.cs#L359) (either the predefined ones with `ExcludeNulls` or by constructing an `Options` passing `excludeNulls: true`).

You may conditionally exclude members by providing [`ShouldSerializeXXX`-methods](https://msdn.microsoft.com/en-us/library/53b8022e(v=vs.110).aspx) (where XXX is the property to control).
