### ISSUE TITLE
overflow in Deserialize list<object> with long decimal value

### ISSUE THREAD

**Issue by Wolfdp** [kevin-montrose/Jil#243]
Exemple:
![001](https://cloud.githubusercontent.com/assets/21313600/18057218/aea0ec2e-6e17-11e6-9b56-3a37e3f9259d.JPG)

problem in method 

namespace Jil.DeserializeDynamic
//...
static partial class Methods
//...
public static uint ReadUIntThunkReader(char firstChar, ref ThunkReader reader, out byte length)
        {
            length = 1;
/\* m.b. use long? */
            uint ret = (uint)(firstChar - '0');

```
        int c;
        while ((c = reader.Peek()) != -1)
        {
            c -= '0';
            if (c < 0 || c > 9) break;

            reader.Read();  // skip digit
            length++;

            ret *= 10;
            ret += (uint)c;
        }

        return ret;
    }
```

**Comment by Tornhoof** [comment]
this bug is specific to the dynamic deserialization, if you deserialize to a known type it apparently does not happen.
