### ISSUE TITLE
Deserialize glitch in 2.14.5 with numbers starting with a .

### ISSUE THREAD

**Issue by bruinjim** [kevin-montrose/Jil#244]
Using c#, the following code generates an error:

dynamic r = JSON.DeserializeDynamic("{\"a\":.1}");

Error: Expected ", [, {, n, t, f, -, 0, 1, 2, 3, 4, 5, 6, 7, 8, or 9; found .

Not sure if starting numbers with a . is part of the json standard, but figured I would post it anyway.

**Comment by YangFan789** [comment]
It is not a part of the JSON spec

**Comment by bruinjim** [comment]
Ah, ok.  Thanks.  :)
