### ISSUE TITLE
containsKey not working?

### ISSUE THREAD

**Issue by bruinjim** [kevin-montrose/Jil#245]
Hello,

Using Jil version 2.14.5

Having some trouble getting containsKey working.

Example:

dynamic r = JSON.DeserializeDynamic("{\"a\":1}");
Console.WriteLine(r.a);
Console.WriteLine(r.containsKey("a"));

Displays the first line, generates an InvalidCastException on containsKey:

An unhandled exception of type 'System.InvalidCastException' occurred in System.Core.dll

Additional information: Unable to invoke dynamic member [containsKey] with args (a) on [{

 "a": 1

}]

**Comment by kevin-montrose** [comment]
`ContainsKey` must be PascalCased, as it's evoking [`IDictionary<T, V>.ContainsKey(T)`](https://msdn.microsoft.com/en-us/library/htszx2dy(v=vs.110).aspx).
