### ISSUE TITLE
Nuget package 2.14.5 and source code 2.14.5 are different

### ISSUE THREAD

**Issue by ArtemAstashkin** [kevin-montrose/Jil#251]
Hello!
According to the issue https://github.com/kevin-montrose/Jil/issues/248 I've downloaded the source code and tried to reproduce the test to find and fix the issue with ArgumentOutOfRangeException:

```
        [TestMethod]
        public void ReproduceOutOfRangeException()
        {
            using (var str = new StringReader("\"0001\""))
            {
                var dto = JSON.DeserializeDynamic(str, Options.ISO8601Utc);

                JSON.SerializeDynamic(dto, Options.ISO8601Utc);
            }
        }
```

I've discovered that the source code had already contained the fix in the file DynamicSerializer.cs at the line 535:
```
if (jilDyn.IsAmbiguousAsDateTime())
{
    dt = DateTimeOffset.MinValue;
    return false;
}
```

I decided to compare (using reflector) the dll from the latest version of Nuget package (2.14.5) and the sources and I didn't find those lines of code.
I've built the dll from the sources and replaced it with dll in the package folder "Jil.2.14.5", tried to run Unit-test in my project and it passed!

I think the latest version (2.14.5) from Nuget and from source code (2.14.5) are different - Nuget package  doesn't contains some fixes or features. 

Can you update the Nuget package to fix this difference and make package actual?
Thanks in advance!

**Comment by kevin-montrose** [comment]
Nuget packages have been updated to latest source.
