### ISSUE TITLE
PeekSupportingTextReader is not required for a StreamReader

### ISSUE THREAD

**Issue by paya-cz** [kevin-montrose/Jil#254]
I am looking at the [MakeSupportPeek](https://github.com/kevin-montrose/Jil/blob/f90ea49f3df3a6dc6222a772e95c5117680e4e69/Jil/Common/ExtensionMethods.cs#L234) method and I wonder, what's the purpose of the check for `asStreamReader.BaseStream.CanSeek`?

The StreamReader implements `Peek` [without any reliance on seeking](https://referencesource.microsoft.com/#mscorlib/system/io/streamreader.cs,353), so shouldn't the condition look like this instead?

    if(asStreamReader != null) return asStreamReader;

This will save us a `PeekSupportingTextReader` allocation and the wrapper overhead.

**Comment by kevin-montrose** [comment]
`StreamReader.Peek()` can return -1 even when the stream has not ended, the conditions are weird and this workaround is imperfect but it happens.

There's a test for this, [`DeserializeTests.SeekNotSupported()`](https://github.com/kevin-montrose/Jil/blob/7921294f9381a8192fbfc006ced42db8d0737935/JilTests/DeserializeTests.cs#L4836).
