### ISSUE TITLE
Global Options

### ISSUE THREAD

**Issue by ehsaanwelcome** [kevin-montrose/Jil#261]
Hi,

1. Is there a way to set options once instead passing in "Serialize function" every time?
2. Is there a way to set "TreatEnumAs" once instead on every required enum field?  
3. Default value on property?

**Comment by benjamin-hodgson** [comment]
[Yep](https://github.com/kevin-montrose/Jil/blob/master/Jil/JSON.cs#L21-L34)

**Comment by lazytom** [comment]
re question 2 I've been looking for that as well, but haven't found. So I started hacking together an implementation ... I might submit a PR once I am done if there is interest ...

re question 3 what do you mean by that?

**Comment by aschekatihin** [comment]
It seems like it isn't possible right now but it'd be nice to have TreatEnumAs as configuration option

**Comment by aschekatihin** [comment]
@lazytom so, do you have a PR for 2?

**Comment by lazytom** [comment]
@aschekatihin I got sidetracked on another project - I think I had it almost done at some point. I will see if I can dig it up and submit ...
