### ISSUE TITLE
Potential Write GUID optimization

### ISSUE THREAD

**Issue by veleek** [kevin-montrose/Jil#262]
I was looking at the [implementation for writing GUIDs](https://github.com/kevin-montrose/Jil/blob/201a611f1589c07b6a65d4fb07bf1d95616bf1e4/Jil/Serialize/Methods.cs#L100), and I was wondering if adding a separate lookup table would improve anything.

Right now you're taking each byte of the GUID and multiplying it by two to get the proper offset into the lookup table.  By splitting the lookup into two parts (first nibble, second nibble) you could do all the lookup without the additional math.

Any possibility of improvement there?

```csharp
static readonly char[] WriteGuidHighLookup = new char[] { '0', '0', '0', '0'... };
static readonly char[]  WriteGuidLowLookup = new char[] { '0', '1', '2', '3'... };

// bytes[0]
buffer[6] = WriteGuidHighLookup[visibleMembers.B00];
buffer[7] = WriteGuidLowLookup[visibleMembers.B00];
...

// or alternatively all the high nibbles first if there
// is overhead for looking up in a different array.
buffer[6] = WriteGuidHighLookup[visibleMembers.B00];
buffer[4] = WriteGuidHighLookup[visibleMembers.B01];
buffer[2] = WriteGuidHighLookup[visibleMembers.B02];
...
```

**Comment by Tornhoof** [comment]
Interesting idea, let's try some microbenchmark for that: https://gist.github.com/Tornhoof/825f881687a79294376404ef4d0a994f

Jil is the original method, Veleek is your first suggestion, Veleek2 is your second one.

``` ini

BenchmarkDotNet=v0.10.5, OS=Windows 10.0.15063
Processor=Intel Core i7-4790K CPU 4.00GHz (Haswell), ProcessorCount=8
Frequency=3906242 Hz, Resolution=256.0005 ns, Timer=TSC
  [Host]     : Clr 4.0.30319.42000, 64bit RyuJIT-v4.7.2046.0
  DefaultJob : Clr 4.0.30319.42000, 64bit RyuJIT-v4.7.2046.0


```
 |  Method |     Mean |     Error |    StdDev |
 |-------- |---------:|----------:|----------:|
 |     Jil | 19.25 ns | 0.0020 ns | 0.0018 ns |
 |  Veleek | 18.08 ns | 0.0398 ns | 0.0372 ns |
 | Veleek2 | 18.86 ns | 0.0524 ns | 0.0437 ns |

So in a dedicated microbenchmark environment your idea might be a few % faster, but as the individual runtimes are already reaching the limits of microbenchmarking, I replaced the single invocations with a loop of 1000 invocations. The output looks like this then:

 |  Method |     Mean |     Error |    StdDev |
 |-------- |---------:|----------:|----------:|
 |     Jil | 19.11 us | 0.0041 us | 0.0030 us |
 |  Veleek | 18.46 us | 0.0078 us | 0.0065 us |
 | Veleek2 | 19.95 us | 0.0062 us | 0.0055 us |

The difference is now much closer and I have no idea why Veleek2 is suddenly slower.

**Comment by veleek** [comment]
Okay, so a little bit faster, but maybe not worth it.  The slowdown in Veleek2 probably has to do with the fact that it has to load the byte value from the GuidStruct twice instead of just once.  

Running the benchmarks on my machine gives slightly better results - ~20%.

Method |     Mean |     Error |    StdDev |
-------- |--------- |---------- |---------- |
Jil | 29.29 ns | 0.6356 ns | 0.9896 ns |
Veleek | 23.24 ns | 0.1770 ns | 0.1656 ns |
Veleek2 | 27.10 ns | 0.3796 ns | 0.3550 ns |
