### ISSUE TITLE
More flexible enums

### ISSUE THREAD

**Issue by VFSwiss** [kevin-montrose/Jil#269]
Hi.

Not sure if I missed this but is there anyway to handle enums more flexibly?

Given `enum Mine { Test }`
I'd like to be able to deserialize both 0 and "Test".
The JilDirective allows my to handle 0 but then "Test" fails.

Also it is very ugly to have to add the directive to every enum property instead of having it globally.
Newtonsoft supports adding a custom JsonConverter to the enum which is a little nicer thamn cluttering the class properties.

Thanks, Vincent

**Comment by paya-cz** [comment]
Also it would be really nice if I could specify `JilDirective` on individual enum values, like this:

```csharp
public enum MessageType
{
    [JilDirective(Name = "one")]
    One,
    [JilDirective(Name = "two")]
    Two,
    [JilDirective(Name = "foo_and_bar")]
    FooBar
}
```
