### ISSUE TITLE
WriteGuid (crazy) suggestion

### ISSUE THREAD

**Issue by smourier** [kevin-montrose/Jil#280]
Hi, this is not an issue, but since you're a fan of crazy optimization :-) , if the code runs on Windows, you could use this other _WriteGuid function that has the advantage of not allocating anything. I think it runs at almost (?) the same speed, but I'm not 100% sure.

    static void _WriteGuid(TextWriter writer, Guid guid, char[] buffer)
    {
        // buffer needs to be at least 39 for B format
        StringFromGUID2(guid, buffer, 39);
        writer.Write(buffer, 1, 36); // strip outer curly braces
    }

    [DllImport("ole32.dll", CharSet = CharSet.Unicode)]
    static extern int StringFromGUID2([MarshalAs(UnmanagedType.LPStruct)] Guid guid, char[] lpsz, int cchMax);

**Comment by Tornhoof** [comment]
Did you benchmark it?
A Pinvoke call will most likely be slower and use more memory for all the marshaling required.

**Comment by smourier** [comment]
I quickly tested it and it seems quite equivalent to Jil's _WriteGuid. There is no marshaling required, these are all in-process pointers.

**Comment by Tornhoof** [comment]
Well you need to do proper benchmarks, I tried and the PInvoke call is close to 100% slower:

``` ini

BenchmarkDotNet=v0.10.9, OS=Windows 10 Redstone 1 (10.0.14393)
Processor=Intel Xeon CPU E5-1620 0 3.60GHz, ProcessorCount=8
Frequency=3507175 Hz, Resolution=285.1298 ns, Timer=TSC
  [Host]     : .NET Framework 4.7 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.2110.0
  DefaultJob : .NET Framework 4.7 (CLR 4.0.30319.42000), 64bit RyuJIT-v4.7.2110.0


```
 |             Method |      Mean |     Error |    StdDev |  Gen 0 | Allocated |
 |------------------- |----------:|----------:|----------:|-------:|----------:|
 |  FormatGuidPInvoke |  44.72 ns | 1.3045 ns | 1.3396 ns |      - |       0 B |
 | FormatGuidToString | 112.99 ns | 2.7242 ns | 4.3990 ns | 0.0198 |     104 B |
 |      FormatGuidJil |  27.84 ns | 0.6098 ns | 0.6525 ns |      - |       0 B |

see https://gist.github.com/Tornhoof/15d12d2cc0fd1d252d2c226ec7d3f310

**Comment by smourier** [comment]
ok, I just tested it in a more global test where it wasn't significant. Interesting to see that p/invoke cost is not that bad, and still 3x faster than .NET's one. I'm surprised FormatGuidJil doesn't show any allocation since it has a new GuidStruct, maybe a compiler's trick.

**Comment by Tornhoof** [comment]
In this case the GuidStruct is allocated on stack.
