### ISSUE TITLE
feature request - dynamic cast to KeyValuePair

### ISSUE THREAD

**Issue by AartBluestoke** [kevin-montrose/Jil#287]
at the moment if you do a dynamic deserialise you get a Jil.DeserializeDynamic.JasonObject object you can't easy interact with. however you can easily iterate its children:

                    foreach (dynamic innerProperty in  dynamicallyDeserialisedJson)
                    {
                        var key = innerProperty.Key; // expensive lookup dynamic function name
                        var value = innerProperty.Value; // expensive lookup dynamic function name
                        ParseFromString(new KeyValuePair<string,dynamic>(key,value));
                    }
The problem is that this is reasonably inefficient running via the dynaimc code with key/function lookups.
The idea code (with the publicly exposed type) should be:

                    foreach (KeyValuePair<string,dynamic> innerProperty in  dynamicallyDeserialisedJson)
                    {
                        ParseFromString(innerProperty);
                    }

It would be nice that a hard cast of innerProperty to a KeyValuePair<string,dynamic> would succeed, efficiently creating a new KeyValue pair without having to run through the layers of dynamic code.

because JsonObject is a dynamic object, this should not be a dangerous or inefficient thing to expose.

**Comment by Tornhoof** [comment]
You can simply cast your dynamic json to ``IDictionary<string,object>`` or ``IDictionary<string,dynamic>``. Then you have your property name in there.

**Comment by Aberro** [comment]
Either I'm doing something wrong or whatever reason, but I can't cast it to neither IDictionary<string, object> nor IDictionary<string, dynamic>, both casts returns null.
And I can see in runtime that behind dynamic is JsonObject with Type == JsonObjectType.Object. So, it's not like I try to cast some string or smth like that.
