### ISSUE TITLE
JSON deserialization fails for List<KeyValuePair<DateTime, double>>

### ISSUE THREAD

**Issue by grisharav** [kevin-montrose/Jil#294]
Using version 
The following:
```C#
        [Test]
        public void TestSerializationDeserializationOfListOfKeyValuePairs()
        {
            var toSerialize = new List<KeyValuePair<DateTime, double>>
            {
                new KeyValuePair<DateTime, double>(DateTime.UtcNow, 5.2),
                new KeyValuePair<DateTime, double>(DateTime.UtcNow.AddDays(1), 6.3),
                new KeyValuePair<DateTime, double>(DateTime.UtcNow.AddDays(2), 7.4),
            };
            var res = JSON.Serialize(toSerialize);
            var deserialized = JSON.Deserialize<List<KeyValuePair<DateTime, double>>>(res);
            CollectionAssert.AreEqual(toSerialize, deserialized);
        }
```

Fails, the deserialization returns list of the correct size but with default initialized values.
Changing KeyValuePair to Custom class/struct works as expected

**Comment by grisharav** [comment]
Any updates on this?

**Comment by Wazner** [comment]
This project is not actively maintained anymore by its owner. If you want something fixed, make a fork and fix it yourself. Or you could use a different JSON serializer.

**Comment by kevin-montrose** [comment]
KeyValuePair<T,V>'s properties are not writable, so while they serialize just fine (the value of `res` is `"[{\"Key\":\"\\/Date(1552519343696)\\/\",\"Value\":5.2},{\"Key\":\"\\/Date(1552605743697)\\/\",\"Value\":6.3},{\"Key\":\"\\/Date(1552692143697)\\/\",\"Value\":7.4}]"`) it's properties cannot be deserialized.

This is complicated a bit by KeyValuePair being a struct, so it can be _constructed_ with it's default parameterless constructor.  If KeyValuePair were instead a class Jil would bomb out at the Deserialize<T> call as no suitable constructor would be available.
