### ISSUE TITLE
JIl Deserialize issue

### ISSUE THREAD

**Issue by DurgaPrasadGavara** [kevin-montrose/Jil#295]
When i convert my object Deserialize, it throwing error.
Error: e.MessageObject reference not set to an instance of an object.e.InnerException.

Sample Object:     varObject = JSON.Deserializet<List<`x`>>((string)HttpContext.Current.Session["Z"]);

**Comment by paval-tech** [comment]
Maybe you should do 
` JSON.Deserialize<List<string>>((string)HttpContext.Current.Session["Z"]));`
instead of 
`JSON.Deserializet<List>((string)HttpContext.Current.Session["Z"]);`

**Comment by DurgaPrasadGavara** [comment]
Thanks, But this is not working.
Sample Object: varObject = JSON.Deserializet<List<object>>((string)HttpContext.Current.Session["Z"]);

**Comment by DurgaPrasadGavara** [comment]
Thanks.

But this also not working.
Sample Object: varObject = JSON.Deserializet<List<obj>>((string)HttpContext.Current.Session["Z"]);

**Comment by DurgaPrasadGavara** [comment]
Thansk. but this is also not working.
Sample Object: varObject = JSON.Deserializet<List<objectsname>>((string)HttpContext.Current.Session["Z"]);

**Comment by DurgaPrasadGavara** [comment]
Thanks,
My object same as above, what you said.
,

**Comment by Wazner** [comment]
I'm sorry, but this issue doesn't contain enough information to determine what is going wrong. Could you provide the following information?
- What is the value of `HttpContext.Current.Session["Z"]`?
  You can view the value in the debugger when the it breaks on the `Exception`.
- What does the type `x` look like?

**Comment by DurgaPrasadGavara** [comment]
The value of HttpContext.Current.Session["Z"] is a list. The List contains list of  objects(type is dashboard). Yes, I can view the value. X is a class name of dashboard.
