### ISSUE TITLE
Serialization calls constructor?!

### ISSUE THREAD

**Issue by Timovzl** [kevin-montrose/Jil#299]
Tracking some strange behaviors, I discovered that a call to `JSON.Serialize(instance, options)` **calls the default constructor of `instance`'s type**.

For completeness, my options are: `new Options(dateFormat: DateTimeFormat.ISO8601, includeInherited: true, serializationNameFormat: SerializationNameFormat.CamelCase, excludeNulls: true)`

Note that we are talking _serialization_, not _deserialization_.

Sure, _deserialization_ might use constructors. I'd rather see it use `FormatterServices.GetUninitializedObject` and avoid touching any potential constructor code, but I've come to expect that most deserialization implementations use constructors.

But touching constructors when _serializing_? I'd consider that a cesspool of unexpected behavior and hard-to-track-down bugs.

I am curious if this is intended behavior and, if so, why.

**Comment by Wazner** [comment]
This only happens the first time a type is serialized. During compilation of a serializer a reflection trick is done to determine the memory layout of a type. Setting fields in sequential order based on their memory address has shown in tests that it increases performance.

**Comment by Timovzl** [comment]
Could this be fixed by doing at least this one-time construction with `FormatterServices.GetUninitializedObject`?

**Comment by Wazner** [comment]
I suppose, the problem with `GetUninitializedObject` is the performance hit.

**Comment by Timovzl** [comment]
If I recall correctly, it is not much worse than `Activator.CreateInstance` or `new T`. And particularly in this case, as a one-time spin-up to improve performance in the long run, it should matter even less, right?

**Comment by kevin-montrose** [comment]
Jil, as a (de)serializer does a lot of janky things to objects and types including spurious constructions.  I strongly advise _not doing anything clever_ in constructors.

I'd advise that for any (de)serializer you use, but Jil is particularly "crazy".

**Comment by Timovzl** [comment]
> Jil, as a (de)serializer does a lot of janky things to objects and types including spurious constructions. I strongly advise not doing anything clever in constructors.

Duely noted!

I had moved away from the library for this reason, although I do not remember the exact scenario. Based on this experience, my hope is that Jil can continue to provide good performance, with less and less monkey business in the future. :)
