### ISSUE TITLE
Jil.StrongName 2.16.0 version supporting netstandard1.6/2.0 and net45

### ISSUE THREAD

**Issue by ianbattersby** [kevin-montrose/Jil#306]
With the recent work to introduce "Microsoft.NetSDK" I wonder if it's possible to release the `2.16.0` version [of `Jil.StrongName`] to nuget.org so that those (like us) who target both platforms don't need a conditional reference and can use the `Jil.StrongName` package for both (as we do for "Polly-Signed").

I appreciate that when building for `netstandard1.6` and `netstandard2.0` the signing _may_ need to be bypassed (we use `<PublicSign Condition="'$(OS)' != 'Windows_NT'">true</PublicSign>` to do this in our assemblies), but it makes for a neater solution I feel.

Happy to do a PR if you agree @kevin-montrose 👍

**Comment by NickCraver** [comment]
Just tidying up issues - Jil.StrongName 2.17.0 is available on NuGet!
