### ISSUE TITLE
how to keep the root class in the serialization?

### ISSUE THREAD

**Issue by nicoclau** [kevin-montrose/Jil#308]
Hello I need to serialize one request.

For example 

class SearchRQ { ...}

But when I serialize, it keeps everything but not the SearchRQ in the string...
var value = Jil.JSON.Serialize(SearchRQ);

I need to see 

{ "SearchRQ" : { ..... } }

Thanks :)

**Comment by Tornhoof** [comment]
You actually want to serialize a type with a  property called ``SearchRQ``.
Easiest way to achieve that ist by wrapping it in such a type.
Try: ``Jil.JSON.Serialize(new { SearchRQ = SearchRQ })``
This creates an anonymous type with that property.

**Comment by nicoclau** [comment]
Thanks for your help, I did about the same thing:

class WrapperRequest
    {
        public SearchRQ SearchRQ { get; set; }
    }

The Json serializer will serialize in  { "SearchRQ": { } }

Thanks.

**Comment by Tornhoof** [comment]
Depending on how your class is designed you might need to use ``SerializeDynamic``
