### ISSUE TITLE
[NotFalse] [NotEmpty] attributes

### ISSUE THREAD

**Issue by arekbulski** [kevin-montrose/Jil#309]
I would like the following code to fail during deserialization (throw an exception) so that I dont need to manually check these fields for their values. Can that be done using JIL? If not, would you be willing to merge a patch for that if I wrote one?
```cs
class S 
{
  [NotNull] [NotFalse] truthy;
  [NotNull] [NotEmpty] text;
}

deserialize any of those, get an exception:
- {truthy: false}
- {text: null}
- {}
```

**Comment by kevin-montrose** [comment]
I would suggest using a different library if you want finer control over validation, Jil is mostly focused on POCOs.

Also, the configuration/options system for Jil is... not great, and I'd want to rework it (and go through a major version bump) before accepting substantial contributions to it.
