### ISSUE TITLE
Heterogeneous arrays

### ISSUE THREAD

**Issue by arekbulski** [kevin-montrose/Jil#310]
Some web apis send arrays of different types of items, its called heterogeneous arrays. This is not a problem on Python, but becomes a problem in a language that has static typing, like C#. Can this be deserialized using JIL, perhaps using some custom type handler? If not, would you merge a patch for that if I wrote it?

```cs
class S
{
  public int A;
  public decimal B;
  public string C;
}

deserialize<S>("[ 1, 2.0, "3" ")
```

**Comment by kevin-montrose** [comment]
The solution to heterogeneous types in C# is normally `dynamic`, like so

```csharp
var dyn = JSON.DeserializeDynamic("[ 1, 2.0, \"3\"]");
int a = dyn[0];    // 1
double b = dyn[1]; // 2
string c = dyn[2]; // 3
```

which is Jil's solution for this.  Generally, once you don't know the types of something it's hard to get (relatively) good performance and at that point it doesn't really matter if you use Jil or something more customizable.
