### ISSUE TITLE
Automatic typename handling

### ISSUE THREAD

**Issue by epicbugs** [kevin-montrose/Jil#311]
Newtonsoft has a concept of [TypeNameHandling](https://www.newtonsoft.com/json/help/html/SerializeTypeNameHandling.htm) which gives the possibility to include type information when serializing JSON so that de-serialization can be successfully completed without any major hassles even in those situations where exact type of incoming message is not known to the receiving application before inspecting that message itself.

Looked around in Options class but couldn't find anything resembling that in Jil.

Could this feature be added? @kevin-montrose

**Comment by Tornhoof** [comment]
You should be extremly careful with ``TypeNameHandling``. It is widely considered a possible security problem. See https://stackoverflow.com/questions/48159442/is-it-possible-to-set-json-net-to-ignore-type and watch the linked video there.

**Comment by epicbugs** [comment]
Interesting. But what can you do when you have literally thousands of different object types coming from an enterprise service bus towards hundreds of different services.

The way we handle that situation is by providing a central client library which does the heavy lifting, along with the help of automatic type name handling.

I'm sure there might be other good (architectural) alternatives to this which give the benefits of a single client library for hundreds of different services and at the same time address security along with relatively painless mapping of thousands of different object types but unfortunately a rather significant investment has already been made, so we won't be re-architecting anything soon.

The reason I posted this questions is because Jil is much much more performant compared to Newtonsoft. If it had automatic type name handling, it would be a no-brainer.

**Comment by kevin-montrose** [comment]
Jil will not be adding this feature.  Generally, I try to keep it as close to "proper" JSON as I can: no comments, no `$type`, etc.

If you need more customization, at least as things are today, I think Newtonsoft is a fine option.
