### ISSUE TITLE
Skip empty collection when serialising

### ISSUE THREAD

**Issue by gfgw** [kevin-montrose/Jil#314]
How can I let Jil skip serialisation of a property that contains an empty collection or dictionary?
We have an object that contains several of these properties, many of which might be empty. Not serialising the empty collections saves space in the resulting json (which is stored in a database).

**Comment by Tornhoof** [comment]
JIL supports the ShouldSerializeXXX pattern https://docs.microsoft.com/en-us/dotnet/framework/winforms/controls/defining-default-values-with-the-shouldserialize-and-reset-methods.

See https://github.com/kevin-montrose/Jil/blob/b022e8442463c9006b861df6bdf174eb679931af/JilTests/SerializeTests.cs#L2520-2541 for an example

**Comment by gfgw** [comment]
Great! Thanks for the example, because the Microsoft page gave me the impression that this only works when using System.Windows.Forms.Controls (which we do not use).
