### ISSUE TITLE
Can you update the support for custom date format?

### ISSUE THREAD

**Issue by penjay** [kevin-montrose/Jil#319]
In our country, yyyy-MM-dd HH:mm:ss is usually used to represent data time.
Ex: 2019-01-26 21:48:45
At present, ISO8601, I have to format every time on the client side.
Thank you.

**Comment by kevin-montrose** [comment]
Adding additional configurations to Jil is troublesome, and will likely remain so for the foreseeable future.

If you need more customization, I'd suggest using a different JSON library.
