### ISSUE TITLE
Loss of Precision when Serializing floats

### ISSUE THREAD

**Issue by dandago** [kevin-montrose/Jil#320]
Hi,

When using this code:

    Console.WriteLine(JSON.Serialize(100921.688f));

I am getting this output:

> 100921.7

I would like to preserve the precision but it seems like the number is being rounded. This behaviour is explained [here](https://stackoverflow.com/a/5987030).

I can see this is happening in this method of `ThunkWriter.cs`:

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void Write(float f)
        {
            Write(f.ToString(CultureInfo.InvariantCulture));
        }

In fact simply doing `100921.688f.ToString()` gives the same result shown earlier.

I've also tried serializing the same thing with JSON .NET and it does not have this problem.

**Comment by Jerome2606** [comment]
I expect the same issue.
I want to switch from JSON.NET to Jil.JSON (faster in installation of my cache).
But it crash while storing double.MinValue and double.MaxValue.
Due to this loss of precision.

**Comment by Jerome2606** [comment]
This should be ok:

value.ToString("R", CultureInfo.InvariantCulture)

**Comment by Jerome2606** [comment]
@dandago I created a PR for this issue. Feel free to use my fork if you need this fix.

**Comment by dandago** [comment]
@Jerome2606 thanks for looking into this.

It has been over a month since I opened this issue, which seems like a stretch for something so small. Is Jil still maintained at all?

**Comment by Jerome2606** [comment]
It seems no, and that's so weird.

I'm using Jil.JSON and Newtonsoft in my production environment. 
Jil.JSON is so much faster for bulk operation (cache initialization) while Newtonsoft is faster for small serialization/deserialization

@kevin-montrose Can you check on the pull request or give the right to anybody to maintain this project ?
