### ISSUE TITLE
Json-Stat dataformat deserialization

### ISSUE THREAD

**Issue by awb99** [kevin-montrose/Jil#323]
I have a somehow stupid usage question: I want to deserialize data in json-stat format.
Now the "dimension" (see below) is basically a Dictionary of a Custom  label-category Data-class.
The only issue is, that 3 elements  that are in this dictionary are of other data-types ("id", "role", "size").
The elements of the label-category data-class are "Indikator" and "Period".

Does anyone know a good way how to deserialize that into a normal class structure?

Thanks!

```
 {"dataset":{
            "label":"The Economic Tendency Indicator and other indicators by Indicator and Period",
            "source":"National institute of economic research",
            "updated":"9999-12-31T22:59:59Z",
            "value":[102.4]
            
            "dimension":{
                "id":["Indikator","Period"],
                "role":{"time":["Period"]}
                "size":[1,1],
                "Indikator": { "label":"Indicator","category": {"index":{"KIFI":0},"label":{"KIFI":"The Economic Tendency Indicator"} }                },
                "Period":{"label":"Period","category":{"index":{"2019M02":0},"label":{"2019M02":"2019M02"}}},
            },
        }}
```

**Comment by kevin-montrose** [comment]
Jil doesn't do much in the way of mapping between different structures (it does some stuff for different formats, and supports wrapping primitives, but not much else).

If you use Jil, you'd probably have to have a set of classes that exactly match what's in the JSON and then a separate chunk of code to map it something normal.

Other JSON libraries (like Newtonsoft's) might be a better fit for your use case, but I'm not familiar enough with it to say for sure.
