### ISSUE TITLE
Case-insensitive deserialize and camelCase serialize options

### ISSUE THREAD

**Issue by swimtver** [kevin-montrose/Jil#35]
It will be great to have this options.

**Comment by jchannon** [comment]
I think case sensitivity is quite a big deal, most json libs support this feature.

**Comment by AlienEngineer** [comment]
+1 for this feature

**Comment by YJingLee** [comment]
+1 for this feature

**Comment by hallvar** [comment]
+1 for this feature

**Comment by NickCraver** [comment]
+1 for this from me too. It'd eliminate a ton of code where this is used. Rather than an ever-increasing `n` attributes (as well as the need for plugin assemblies to have dependencies in a CoreCLR world), a Jil option controlling serialization globally would be much more optimal.

**Comment by RefactorMan** [comment]
+1

**Comment by Wazner** [comment]
For anyone reading this issue and hasn't looked at the pull requests yet.
There is currently a pull request that implements camelCasing.

See #154
