### ISSUE TITLE
Deserialize without generic type-parameter but.. with.. Type parameter?

### ISSUE THREAD

**Issue by joergbattermann** [kevin-montrose/Jil#60]
Good evening,

I was wondering whether there is any existing or a planned way to deserialize a string or stream into an object instance, without providing the target type via a <T> type parameter, but via the "good old" Type parameter in the Json.Deserialize(..) signature, e.g.:

using(var input = new StringReader(myString))
    {
        var myTargetType = typeof(MyClass);
        var result = JSON.Deserialize(input, myTargetType);
    }

I know it doesn't exist atm and I would not want to use reflection to call your existing generic method via reflection to achieve that (ick: http://stackoverflow.com/questions/2107845/generics-in-c-using-type-of-a-variable-as-parameter) unless I had to. Right now I am attempting to plug Jil into NancyFx as a custom (De-)Serializer and their IBodySerializer signature only provides the target type as a plain Type parameter value, not as a <T> type parameter.

Is there any chance that might be added to Jil as an alternative to the existing JSON.Deserialize<MyClass> method?

Cheers and thanks,
-J

**Comment by dotjosh** [comment]
Is there a way to serialize and pass the type too?  I have a collection of objects that are used as their base type, so the generic method isn't serializing any properties defined on the subclass because the type is inferred from the generic signature of JSON.Serialize().

**Comment by kevin-montrose** [comment]
@dotjosh `JSON.SerializeDynamic(object, Options)` probably does what you want there.  There's a perf hit (since it has to inspect), but if none of your types are DLR-aware then it shouldn't be a big one.

**Comment by dotjosh** [comment]
Thank you - yeah I saw that, didn't realize it was applicable.  I'll have
to test the performance.  The primary reason I'm looking at the library
(over newtonsoft) is the perf..
