### ISSUE TITLE
Local DateTime troubles

### ISSUE THREAD

**Issue by oliverjanik** [kevin-montrose/Jil#79]
I'm a big fan of Jil but it seems its still not mature enough. DateTimes have become a pet peeve of mine. Almost all json serializers out there get DateTimes wrong without extensive configuration.

DateTime in .Net has a kind attached. Which can be one of three things Local, Utc or Unspecified. I believe Jil should behave differently for ISO8601 format.

Currently doing:

    JSON.Serialize(DateTime.Now, new Options(dateFormat: DateTimeFormat.ISO8601))

returns:

     "2014-10-09T01:25:08.5660994Z"

This is wrong. Local or Unspecified DateTime should not be converted to UTC because makes it impossible to convert back to local time for the receiver unless the original timezone is known. The output I would expect would be:

    "2014-10-09T012:25:08.5660994"

You can probably tell which time zone im in right now ;-)

For greater discussion please read about NodaTime concepts http://blog.nodatime.org/2011/08/what-wrong-with-datetime-anyway.html by Jon Skeet

**Comment by mrgonext** [comment]
I had the same, please fix it as soon as you can.

**Comment by yyooda** [comment]
me too.

**Comment by yyoda** [comment]
me too.

**Comment by kevin-montrose** [comment]
It is now (as of [2.8.0](https://www.nuget.org/packages/Jil/2.8.0)) possible to change Jil's treatment of `DateTimeKind.Unspecified`, with [`Options`](https://www.nuget.org/packages/Jil/2.8.0) and [`UnspecifiedDateTimeKindBehavior`](https://github.com/kevin-montrose/Jil/blob/master/Jil/UnspecifiedDateTimeKindBehavior.cs).  DateTimeOffset will now preserve time zone information as well.

The default behavior remains treating Unspecified as Local, and `DateTime` will continue to be serialized and deserialized in UTC for round-tripping purposes.

**Comment by yufhoyos** [comment]
i got the same problem on 2.9 version, it is ignoring the option UnspecifiedDateTimeKindBehavior.

**Comment by kevin-montrose** [comment]
@yufhoyos care to post a reproduction?

**Comment by yufhoyos** [comment]
_jilOptions = new Options(dateFormat: DateTimeFormat.NewtonsoftStyleMillisecondsSinceUnixEpoch, unspecifiedDateTimeKindBehavior: UnspecifiedDateTimeKindBehavior.IsLocal);

  JSON.Serialize(value, streamWriter, _jilOptions);

currently my local zone is gtw -5 (Bogota,Lima,Quito), i tried with isUTC or Islocal and i have the same result de 'Z'  at the end of the date and the same hour ignoring mi local time.

or a miss a setting?

**Comment by kevin-montrose** [comment]
As noted in [Configuration](https://github.com/kevin-montrose/Jil#configuration) a `DateTime` will always be converted to UTC time for serialization, `UnspecifiedDateTimeKindBehavior` controls how that conversion is done.  DateTimes are either [Local, Utc, or Unspecified](https://msdn.microsoft.com/en-us/library/shx7s921%28v=vs.110%29.aspx); converting the first two to UTC is well defined, converting the last is configurable (default is to treat it as a Local kind).

Jil converts `DateTimes` because they don't carry proper time zone information.  If you want to avoid conversion to UTC, you have to use a `DateTimeOffset`.

To illustrate the difference between `DateTime` and `DateTimeOffset`, if I run the following (in the Eastern US time zone):
```
DateTime now = DateTime.Now;
DateTimeOffset nowDto = now;

Console.WriteLine(now.ToString());

var options = new Options(dateFormat: DateTimeFormat.ISO8601, unspecifiedDateTimeKindBehavior: UnspecifiedDateTimeKindBehavior.IsLocal);

Console.WriteLine(JSON.Serialize(now, options));

Console.WriteLine(JSON.Serialize(nowDto, options));
```

I get:
```
3/19/2015 1:12:19 PM
"2015-03-19T17:12:19.5632024Z"
"2015-03-19T13:12:19.5632024-04:00"
```

The difference between `UnspecifiedDateTimeKindBehavior` can be shown with:
```
DateTime dt = new DateTime(2015, 3, 19, 0, 0, 0, DateTimeKind.Unspecified);

Console.WriteLine(dt.ToString());

var asLocalOpts = new Options(dateFormat: DateTimeFormat.ISO8601, unspecifiedDateTimeKindBehavior: UnspecifiedDateTimeKindBehavior.IsLocal);
var asUtcOpts = new Options(dateFormat: DateTimeFormat.ISO8601, unspecifiedDateTimeKindBehavior: UnspecifiedDateTimeKindBehavior.IsUTC);

Console.WriteLine(JSON.Serialize(dt, asLocalOpts));

Console.WriteLine(JSON.Serialize(dt, asUtcOpts));
```

Which gives:
```
3/19/2015 12:00:00 AM
"2015-03-19T04:00:00Z"
"2015-03-19T00:00:00Z"
```
