### ISSUE TITLE
Make ISO8601 default DateTime format

### ISSUE THREAD

**Issue by oliverjanik** [kevin-montrose/Jil#80]
Can we please leave the past behind and leave the bastardized non standard `\/Date(...)\/` notation in for the historians and masochists? 

It is great to have the optional configuration for backwards compatibility but it should not be the default.

The crazy non-standard format wasn't even invented by Newtonsoft.Json. They took it from `JavascriptSerializer`. http://james.newtonking.com/json/help/index.html?topic=html/DatesInJSON.htm

For the happiness of future generationa let's not propagate this non-sense further more.

**Comment by mj1856** [comment]
Please consider reopening this.  The old format needs to die.
