### ISSUE TITLE
Help on Deserializing

### ISSUE THREAD

**Issue by Wiss911** [kevin-montrose/Jil#90]
Hey, 

i read today about this deserializer and wanted to test it. I want to deserialize a webresponse which includes Json-Data with deserialize<t> to my defined object.. But i always get the following error. Am i doing something wrong or do i need to adjust the parameters?

Message: Expected: {, null
Stacktrace:   bei _DynamicMethod0(TextReader , Int32 )
   bei Jil.JSON.Deserialize[T](TextReader reader, Options options) in c:\Users\kmontrose\Dropbox\jil\Jil\JSON.cs:Zeile 629.

This is how i run it: 

using (var input = new StringReader(await Message.Content.ReadAsStringAsync()))
               {
var result = Jil.JSON.Deserialize<T>(input);
}

This is the example Json i get in the response: 

{"currencies":[{"name":"COINS","funds":500,"finalFunds":500},{"name":"POINTS","funds":0,"finalFunds":0}],"auctionInfo":[{"buyNowPrice":7800,"itemData":{"id":38776970722,"timestamp":1413479494,"itemType":"player","formation":"f4231","assetId":165229,"pile":5,"rating":81,"teamid":1,"training":0,"untradeable":false,"leagueId":0,"resourceId":1879213421,"contract":6,"injuryType":"none","injuryGames":0,"suspension":0,"morale":50,"fitness":57,"assists":0,"cardsubtypeid":1,"discardValue":648,"itemState":"forSale","preferredPosition":"CB","lastSalePrice":7200,"owners":4,"rareflag":1,"attributeList":[{"value":81,"index":0},{"value":40,"index":1},{"value":62,"index":2},{"value":65,"index":3},{"value":82,"index":4},{"value":75,"index":5}],"statsList":[{"value":0,"index":0},{"value":0,"index":1},{"value":0,"index":2},{"value":0,"index":3},{"value":0,"index":4}],"lifetimeStats":[{"value":35,"index":0},{"value":3,"index":1},{"value":1,"index":2},{"value":0,"index":3},{"value":0,"index":4}],"playStyle":250,"lifetimeAssists":1,"loyaltyBonus":0},"tradeId":13466225834,"currentBid":0,"offers":0,"watched":null,"bidState":"none","tradeState":"active","startingBid":7700,"expires":33,"sellerName":"Hamburg FC","sellerEstablished":1409109364,"sellerId":0},{"buyNowPrice":8800,"itemData":{"id":44269376297,"timestamp":1415214839,"itemType":"player","formation":"f4222","assetId":165229,"pile":5,"rating":81,"teamid":1,"training":0,"untradeable":false,"leagueId":0,"resourceId":1879213421,"contract":11,"injuryType":"none","injuryGames":0,"suspension":0,"morale":50,"fitness":89,"assists":1,"cardsubtypeid":1,"discardValue":648,"itemState":"forSale","preferredPosition":"CB","lastSalePrice":9700,"owners":3,"rareflag":1,"attributeList":[{"value":81,"index":0},{"value":40,"index":1},{"value":62,"index":2},{"value":65,"index":3},{"value":82,"index":4},{"value":75,"index":5}],"statsList":[{"value":25,"index":0},{"value":1,"index":1},{"value":5,"index":2},{"value":1,"index":3},{"value":0,"index":4}],"lifetimeStats":[{"value":25,"index":0},{"value":1,"index":1},{"value":5,"index":2},{"value":1,"index":3},{"value":1,"index":4}],"playStyle":264,"lifetimeAssists":1,"loyaltyBonus":1},"tradeId":13466222807,"currentBid":0,"offers":0,"watched":null,"bidState":"none","tradeState":"active","startingBid":7800,"expires":34,"sellerName":"VIVA RONALDO","sellerEstablished":1288808184,"sellerId":0}],"credits":500,"errorState":null,"duplicateItemIdList":null,"bidTokens":{}}

**Comment by Charuwaka** [comment]
Hi @kevin-montrose 

it's great that JIL can serialize and Deserialize by couple of Milliseconds less time compared to JSON.NET,but only problem i see matching model exactly to datatypes,in case of json.net we didn't find any problem while serialize and Deserialize, so can you please make tool which generate Model perfectly depending on Json , so that JIL can serialize and Deserialize  properly.
