### ISSUE TITLE
Dynamic Modify Json

### ISSUE THREAD

**Issue by kevin-aoenen** [kevin-montrose/Jil#91]
Jil Have the function of this
Newtonsoft.net 
string str = JsonConvert.SerializeObject(object);
            var jobj = JObject.Parse(str);
            jobj.Remove(propertyName);

**Comment by kevin-montrose** [comment]
I prefer to keep the models returned by `DeserializeDynamic` immutable.  If modification were allowed there's no guarantee that passing a `dynamic` created by Jil to `SerializeDynamic` would succeed, at least without doing a lot of checking around types and reference loops.

**Comment by ferchoMancini** [comment]
How about values? should we be able to edit?
