### ISSUE TITLE
Deserialize can't deserialize inherited properties with private set

### ISSUE THREAD

**Issue by maurodx** [kevin-montrose/Jil#94]
I'm testing simple class with an auto-property with a private set.
Jil can do serialization and deserialization with no problems if this private set auto-property is on the class being serialized/deserialized but if the private set auto-property is on a base class and my class inherit from it Jil can't deserialize and return null for that property.

I can't mark the setter internal or protected because I want a class method to do property set.

Looking at the code I see that properties with no setmethod are excluded from deserialization but the property have the SetMethod if we look the same property from the correct declaring type.

**Comment by gdoron** [comment]
@maurodx That's odd, I see that Jil doesn't serialize public Auto-properties with private setters even in the declaring class (not inherited property).

Anyway @kevin-montrose, should Jil support private setters?

**Comment by kamil-mrzyglod** [comment]
+1 @kevin-montrose Any info on that?

**Comment by gfgw** [comment]
I know this is an old issue, but since it is still open, and I am running into the same problem.
(When) will this issue be fixed? Is there a workaround?
